### ISSUE TITLE
GitHub Actions: Include OpenJDK binaries file in release (for building IKVM from source)

### ISSUE THREAD

**Issue by NightOwl888** [ikvmnet/ikvm#131]
This should be an easy task for those who wish to help us out. We are already building `openjdk-build-linux-x86_64-normal-server-release.zip` and [uploading it as a GitHub Actions artifact](https://github.com/ikvm-revived/ikvm/blob/develop/.github/workflows/IKVM.yml#L84-L88), however, there are a couple of issues:

1. The [GitHub Release](https://github.com/ikvm-revived/ikvm/releases) doesn't include the file.
2. The file was historically named after the JDK tag that it is based upon with an `openjdk-` prefix and `-stripped.zip` suffix (for example, [openjdk-8u45-b14-stripped.zip](https://github.com/ikvm-revived/ikvm/releases/download/8.1.5717.0/openjdk-8u45-b14-stripped.zip) is based on the [tag `Jdk8u45-b14`](https://github.com/openjdk/jdk8u/tree/jdk8u45-b14))). The file included a folder within named `linux-x86_64-normal-server-release` that contain the OpenJDK contents.

This file is not required for normal IKVM usage, but its contents are required to be placed in the `<repo-root>/openjdk/build/linux-x86_64-normal-server-release` folder in order to compile IKVM from source and run the tests locally.

> **NOTE:** Although the folder name says "linux", it will build on Windows also.

Historically, IKVM has always included the JDK binary file that corresponds to a given release so it is clear which version to use when building from a specific repository tag from source. We have recovered the historical files from the internet archive and placed them in this repository. For example [8.1.5717.0](https://github.com/ikvm-revived/ikvm/releases/tag/8.1.5717.0) includes the `openjdk-8u45-b14-stripped.zip` file. This will become important again when we upgrade to a newer JDK version (see #120), since without this in place it is not clear what version of OpenJDK a specific IKVM release depends on.

**Comment by kevincrans** [comment]
That is under a different license, so I vote against this idea.

**Comment by kevincrans** [comment]
I hope it will not be in the default binary, since it would require users to agree to different license terms.
It's also not necessary if you develop with Kotlin.

**Comment by kevincrans** [comment]
I might have not understood correctly.
But I recommend keeping the option to have a binary that doesn't ship with jdk, for people who use Kotlin instead.

**Comment by NightOwl888** [comment]
I meant to include the file in the GitHub Release (which we have done already for legacy versions). It won't be distributed on NuGet - you would need to download it separately. And it is basically only useful if you build IKVM from source.

**Comment by wasabii** [comment]
Closing this bug in favor of #321
