### ISSUE TITLE
GitHub Actions: Run tests with --blame-crash and --blame-hang options

### ISSUE THREAD

**Issue by NightOwl888** [ikvmnet/ikvm#132]
Testing on .NET Core requires [`--blame-crash` and `--blame-hang`](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-test#options) to catch issues that throw exceptions that the runtime itself cannot catch (i.e. `StackOverflowException`). These can be used to force the build to fail (it makes the `dotnet test` command return a non-zero exit code) when an error happens or the tests fail to complete rather than the default behavior of "ignore and continue" and return exit code 0.

Note that these options don't have any effect on .NET Framework or .NET Core 3.x tests, but can be included with no ill effects.

## `--blame-hang`

- `--blame-hang-dump-type mini` (this implies `--blame-hang`)
- `--blame-hang-timeout 20min` (this implies `--blame-hang`)

This will take some trial and err to ensure we have the correct timeout. Note the GitHub Actions agents have a limit of 1 hour. I would suggest using 20 minutes as a starting point to see if that is long enough to make all of the tests complete We may need to adjust this from time to time, so ideally it would be stored in a variable.

## `--blame-crash`

- `--blame-crash-dump-type mini` (this implies `--blame-crash`)

The commands to modify are [here for Windows](https://github.com/ikvm-revived/ikvm/blob/0709afc1fe3922324ba9b680dc5b8a03c8a294c5/.github/workflows/IKVM.yml#L247) and [here for Linux](https://github.com/ikvm-revived/ikvm/blob/0709afc1fe3922324ba9b680dc5b8a03c8a294c5/.github/workflows/IKVM.yml#L281).

We may need to adjust how the commands are run to ensure the exit code causes a build failure, since they are running inside of a `pwsh` shell.

**Comment by wasabii** [comment]
This is done.
