### ISSUE TITLE
AWT

### ISSUE THREAD

**Issue by GeorgeS2019** [ikvmnet/ikvm#144]
Not relevant

**Comment by wasabii** [comment]
AWT is presently unsupported.

**Comment by GeorgeS2019** [comment]
In preparation for ikvm in linux dotnet,  the Windows specific image creation and manipulation may need e.g. ImageSharp

**Comment by wasabii** [comment]
It's not supported on Windows either.

**Comment by GeorgeS2019** [comment]
> ImageSharp: A modern, cross-platform, 2D Graphics library for .NET

**Comment by wasabii** [comment]
AWT is a windowing toolkit. I can't quite figure out what you're suggesting.

**Comment by wasabii** [comment]
Headless mode might work.

**Comment by wasabii** [comment]
Will leave this issue around to discuss eventual AWT support.

Ideas:

First off, I think abandoning the existing WinForms support is probably the right thing to do, at least for now.  It needs a serious reassessment for Core anyways.

I think a better initial strategy would be to port the actual OpenJDK AWT toolkits to IKVM. They consist currently of mostly native callouts to existing Windowing libraries: Win32, GTK, etc. I think it would be fine to consider compiling the actual C of this, and having it distributed in some separate OS specific packages. IKVM.Java.AWT.Windows, IKVM.Java.AWT.GTK, or something.

Given how well JNI works, this shouldn't actually be much of a problem. We get to make the thing work while not having to write much code of our own.

If somebody wants to, they can implement a managed AWT toolkit.

**Comment by GeorgeS2019** [comment]
```java
Exception in thread "Thread-1" java.lang.Error: Could not find class: ikvm.awt.NetGraphicsEnvironment, @AWTASSEMBLY@
        at java.awt.GraphicsEnvironment.createGE(GraphicsEnvironment.java:116)
        at java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:81)
        at java.awt.image.BufferedImage.createGraphics(BufferedImage.java:1356)
```

**Comment by wasabii** [comment]
I don't know what that error is in reference to. You're going to have to be more specific.

**Comment by GeorgeS2019** [comment]
`JFrame frame = new JFrame();`

`Could not find class: ikvm.awt.NetGraphicsEnvironment, @AWTASSEMBLY@`

**Comment by wasabii** [comment]
AWT is not supported.......

**Comment by GeorgeS2019** [comment]
Just curious, what were not brought forwards to the ikvm-revived that allow the e.g. JFrame  and other AWT to work?

**Comment by wasabii** [comment]
IKVM.AWT.WinForms, which is the AWT toolkit implemented on top of WinForms. It was never a very well-completed project, and ended up pretty broken on Core.

**Comment by GeorgeS2019** [comment]
Since you are using System.Drawing.Common
We could have access to Bitmap according to this [discussion ](https://stackoverflow.com/questions/54180326/net-core-unable-to-use-bitmap)

The main challenges now are Java.awt.Graphics, Graphics2D etc. 

I am hacking an ugly way to get System.Drawing.Graphics from Bitmap. 

What do you think? I am very curious HOW WOULD YOU DO IT differently  considering there are a few Cross platform .NET Gui

I know you said before e.g. JNI etc.

**Comment by wasabii** [comment]
I don't understand the question. Do what? This thread is about AWT, but none of your questions seem to have to do with AWT.

**Comment by GeorgeS2019** [comment]
@wasabii  You have done an excellent JOB!

We respect your vision. We seek your thinking process since you moved forwards with the IKVM project to an extent no one thought it was possible.

**Comment by GeorgeS2019** [comment]
@wasabii  

**Thank you,** the ported .NET Core IKVM has performed better than my previous experience with .NET Framework.

**Comment by GeorgeS2019** [comment]
#### ikvm.awt.[NetToolkit](https://github.com/ikvm-revived/ikvm/blob/9429bc3b697e1b0b2adb6b29e91870ab22f96999/src/IKVM.AWT.WinForms/toolkit-0.95.cs#L327)

**Comment by GeorgeS2019** [comment]
There are from the Nuget (.NETFramework) distributed by
https://github.com/windward-studios/ikvm8

![image](https://user-images.githubusercontent.com/49812372/192630989-909b6338-7798-437b-b957-bebb372daaff.png)

![image](https://user-images.githubusercontent.com/49812372/192631166-38770890-d492-4545-bef8-2a129ffc6d72.png)

![image](https://user-images.githubusercontent.com/49812372/192631485-a0234372-e2f9-48f9-a923-2653c444d44d.png)

**Comment by GeorgeS2019** [comment]
#### Ikvm WINWARD
![image](https://user-images.githubusercontent.com/49812372/192631485-a0234372-e2f9-48f9-a923-2653c444d44d.png)

### ikvm-revived
![image](https://user-images.githubusercontent.com/49812372/192632052-f76b7778-f0b5-4d30-afa3-22742bc2779c.png)

**Comment by GeorgeS2019** [comment]
@jfrijters 

Not sure if you are still around, if so, do you think it is feasible to make IKVM.AWT.WinForm to work ONLY for Windows under .NET Core?

**Comment by GeorgeS2019** [comment]
Can someone show me how to run and test in headless way for IKVM.AWT.WinForm?

**Comment by GeorgeS2019** [comment]
### .NET6-Window version
 of IKVM.AWT.WinForm
![image](https://user-images.githubusercontent.com/49812372/192633799-4edbd567-1c6d-4b0c-8fae-522e6c56bb0c.png)

**Comment by wasabii** [comment]
You should probably not bother Jeroen. He is unlikely to answer.

>Why in ikvm-revived these are not included in Ikvm.Runtime.JNI?

The native libraries encompassed two parts originally: the JNIEnv bridge, and a number of on-off functions used in various parts of IKVM (mmap, few other minor things). The mmap stuff was removed (by me). All that remains is the JNIEnv bridge. And that continues to live in the ikvm-native library.

**Comment by wasabii** [comment]
>Can someone show me how to run and test in headless way for IKVM.AWT.WinForm?

What tests? What are you talking about?

**Comment by GeorgeS2019** [comment]
@wasabii 

What u mean by this? Thanks
![image](https://user-images.githubusercontent.com/49812372/192635321-5e4969a5-b582-48c5-ba1c-c918cb38e9f8.png)

**Comment by wasabii** [comment]
Yes, but what tests?

**Comment by wasabii** [comment]
Java has a headless mode. Look it up.

**Comment by wasabii** [comment]
>Will leave this issue around to discuss eventual AWT support.

**Comment by wasabii** [comment]
Please do not close this issue, as it represents actual future work that should be accomplished.

**Comment by GeorgeS2019** [comment]
https://github.com/ikvmnet/ikvm/pull/528

**Comment by GeorgeS2019** [comment]
@lytico
I downloaded the nuget from the awt action artifact. 
Then I simply run this [code](https://[raw.githubusercontent.com/ikvmnet/ikvm/awt/src/IKVM.ConsoleApp/Program.cs](https://raw.githubusercontent.com/ikvmnet/ikvm/awt/src/IKVM.ConsoleApp/Program.cs))
![image](https://github.com/ikvmnet/ikvm/assets/49812372/25e9ea58-c07b-4b1f-8c84-47a7d2bcafb4)

**Comment by wasabii** [comment]
AWT support merged into develop branch.

**Comment by GeorgeS2019** [comment]
Using the latest **8.9.0 preview**
**Strange font** remain. 


<img src="https://github.com/ikvmnet/ikvm/assets/49812372/df71ef0a-910d-430b-86a1-0d5c8fa7570f)" width=150>


```cs
using System.Diagnostics;

using java.awt;

namespace IKVM.ConsoleApp
{

    public static class Program
    {
        public static void Main(string[] args)
        {
            while (!Debugger.IsAttached)
                System.Threading.Thread.Sleep(100);

            AWTExample1.Foo();

            java.lang.System.@out.println("hi");
            System.Console.ReadLine();
        }

        public class AWTExample1 : Frame
        {

            AWTExample1()
            {
                var t = new TextField("THIS IS TEXT");
                t.setBounds(30, 30, 80, 30);
                add(t);

                var b = new Button("1234");
                b.setLabel("1234");
                b.setBounds(30, 100, 80, 30);
                add(b);

                var b2 = new Button("1234");
                b2.setLabel("1234");
                b2.setBounds(30, 200, 80, 30);
                add(b2);

                setSize(300, 300);
                setTitle("This is our basic AWT example");
                setLayout(null);
                setVisible(true);
            }

            public static void Foo()
            {
                new AWTExample1();
            }

        }

    }

}
```
