### ISSUE TITLE
IKVMC.exe .net core "INTERNAL COMPILER ERROR" 

### ISSUE THREAD

**Issue by Tenali7** [ikvmnet/ikvm#183]
I tried converting a jar to dll, using net461\any\IKVMC.exe. The exe throws a fatal error IKVMC5025 exception

![image](https://user-images.githubusercontent.com/19690231/195646776-09fda670-120b-4452-bbe2-4e675307f8b1.png)

And I tried the netcoreapp3.1\win7-x64\ikvmc.exe, this results in a runtime exception ("INTERNAL COMPILER ERROR")

![image](https://user-images.githubusercontent.com/19690231/195647437-4b632220-9423-415e-9e63-1d55dd19b8ae.png)

Am I missing something? 

Downloaded IKVM 8.2.1 from Nuget.

**Comment by wasabii** [comment]
Yeah. There are a lot of options you need to pass. It is easier for beginners to use IkvmReference or MavenReference.

Consult the README on the nuget package.

**Comment by Tenali7** [comment]
@wasabii 
Thanks for the heads up, managed to create a jar to .dll using the ikvmReference.

The output DLL is empty and does not have any of the JAR-specific types 

![image](https://user-images.githubusercontent.com/19690231/195656488-36b25206-f0a3-41ef-952e-cd430eafbcad.png)

**Comment by wasabii** [comment]
You're going to have to look at the build output.

**Comment by Tenali7** [comment]
@wasabii, if you are referring to build output messages, zero failed. No Warning or Error was reported.
![image](https://user-images.githubusercontent.com/19690231/195662144-fe396d6d-f731-4a02-8866-78f2675c0b69.png)

**Comment by wasabii** [comment]
Clear the file from the ikvm cache and build again.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Tenali7** [comment]
@wasabii , I use Windows Laptop, and I think there is no Home folder.  However, I cleared %temp% folder. 

Created a new test project, added project reference to IKVM from Nuget package manager
Configured the IKVMReference

![image](https://user-images.githubusercontent.com/19690231/195677738-6864ee5d-a7f7-4df7-b39e-8c4dd61ea56e.png)

The DLL is created, but it is blank, no types
![image](https://user-images.githubusercontent.com/19690231/195678090-7ff0453c-2893-403d-9372-7912fe9bfd5f.png)

![image](https://user-images.githubusercontent.com/19690231/195676096-16c45345-4bf7-4e30-bd97-b7dc464a8396.png)

![image](https://user-images.githubusercontent.com/19690231/195676955-53139744-05de-4562-86d8-87e253a8fdb3.png)

I notice a .rsp file, which has reference and output details

![image](https://user-images.githubusercontent.com/19690231/195676631-8882db85-9ff9-4543-ae87-9871bd2d3d19.png)

Build Output:

![image](https://user-images.githubusercontent.com/19690231/195676817-afc18d81-1e97-4dd9-ae94-ef7b02fd0398.png)

I still don't know why the DLL has no C# /.net Types

**Comment by Tenali7** [comment]
I tried and had no luck. The output dll is blank, and no types are exported.

**Comment by Tenali7** [comment]
@wasabii I used an older version of IKVM, good thing is it is not crashing but it is complaining the class format (number) is not supported.  Do you know how to find out which version of Java is expected by the IKVM?  

![image](https://user-images.githubusercontent.com/19690231/195867961-f4a023a9-07d6-437b-9cc7-fb6dbda781f4.png)

**Comment by wasabii** [comment]
Versions below 8.2 are not supported by us.

**Comment by wasabii** [comment]
That said, as the README says, IKVM only supports JDK8 classes. That's what that error is about.
