### ISSUE TITLE
.NET 6 Compilation

### ISSUE THREAD

**Issue by wasabii** [ikvmnet/ikvm#204]
Right now ikvmc and ikvmstub can only generate .NET 3.1 or NET461 output. This is due to various hard coded assembly/type references. And some weird unification table.

**Comment by GeorgeS2019** [comment]
@wasabii  Excellent job!!!! Do u think .NET 6 is feasible end of this year? :-)

**Comment by wasabii** [comment]
I have no idea.

**Comment by wasabii** [comment]
#401
