### ISSUE TITLE
Target ResolveIkvmRuntimeAssembly not available when trying to use IKVM.NET.Sdk/8.4.0

### ISSUE THREAD

**Issue by martin-honnen** [ikvmnet/ikvm#230]
I am trying to use IKVM.NET.Sdk/8.4.0 but I am not getting far, a simple test project https://github.com/martin-honnen/IKVM840Test1 doesn't build with an error 
`1>C:\Users\marti\.nuget\packages\ikvm.net.sdk\8.4.0\targets\IKVM.Java.Core.targets(24,44): error MSB4057: Das Ziel "ResolveIkvmRuntimeAssembly" ist im Projekt nicht vorhanden.`

My translation is 
`1>C:\Users\marti\.nuget\packages\ikvm.net.sdk\8.4.0\targets\IKVM.Java.Core.targets(24,44): error MSB4057: The target "ResolveIkvmRuntimeAssembly" is not available in the project.`

Have I failed to construct the file https://github.com/martin-honnen/IKVM840Test1/blob/master/IKVM840Test1/IKVM840Test1.msbuildproj with the contents

```
<Project Sdk="IKVM.NET.Sdk/8.4.0">
    <PropertyGroup>
        <TargetFrameworks>netcoreapp3.1</TargetFrameworks>
    </PropertyGroup>
    <ItemGroup>
      <Compile Remove="Test1.java" />
    </ItemGroup>
    <ItemGroup>
      <None Include="Test1.java" />
    </ItemGroup>
</Project>
```

properly?

**Comment by wasabii** [comment]
It had that little yellow warning on it for a good 5 minutes before it figured things out.

**Comment by wasabii** [comment]
Curiously how fast is your internet connection? The biggest delay in it figuring things out is it has to download all the NuGet packages in the background. And it's almost over a GB in size at this point.

**Comment by wasabii** [comment]
IKVM.msbuild.tools, and half a dozen more for each supported runtime target

**Comment by martin-honnen** [comment]
I have directories
```
ikvm.msbuild.tools 66 KB
ikvm.msbuild.tools.runtime.linux-arm 271 MB
ikvm.msbuild.tools.runtime.linux-arm64 256 MB
ikvm.msbuild.tools.runtime.linux-x64 269 MB
ikvm.msbuild.tools.runtime.win7-x64 253 MB
```

according to Windows Explorer

**Comment by martin-honnen** [comment]
No, it doesn't appear to be able to do that, yellow (or rather brown) exclamation mark on all dependencies like framework `Microsoft.NETCore.App`, packages `IKVM 8.4.0`, `IKVM.MSBuild 8.4.0`.

**Comment by wasabii** [comment]
Try running dotnet restore on it from the command line.

**Comment by martin-honnen** [comment]
It does that without showing any errors

```
C:\Users\marti\source\repos\IKVM840Test1\IKVM840Test1>dotnet restore
  Wiederherzustellende Projekte werden ermittelt...
  "C:\Users\marti\source\repos\IKVM840Test1\IKVM840Test1\IKVM840Test1.msbuildproj" wiederhergestellt (in "483 ms").
```

but none of the exclamation marks vanish, not even after unloading and reloading the project.

Not even cleaning the project runs through successfully.

The only "progress" I have now after closing all VS instances and solely reopening that one project is that the dependency of the `Frameworks/Microsoft.NETCore.App` no longer has the exclamation mark.

Well, I have to look for some other way to get that going, so far that seems all to be too frustrating.

**Comment by GeorgeS2019** [comment]
@martin-honnen 
Having similar problem with 

TestBuildJava.msbuildproj
```xml
<Project Sdk="IKVM.NET.Sdk/8.4.5">
  <PropertyGroup>
    <TargetFrameworks>netcoreapp3.1</TargetFrameworks>
  </PropertyGroup>
  <ItemGroup>
    <None Include="Test1.java" />
  </ItemGroup>
</Project>
```

The project 'TestBuildJava' ran into a problem during the last operation: The value of the 'TargetFrameworkMoniker' and 'NuGetTargetMoniker' properties in the 'Debug|AnyCPU' configuration are both empty. This configuration will not contribute to NuGet restore, which may result in restore and build errors. You may need to reload the solution after fixing the problem.

**Comment by wasabii** [comment]
Any chance you want to give this another go on 8.5.0?

There was another fellow who opened a bug today, and commented how awesome he found IKVM.Net.SDK. And how well it worked.

So I'm pretty sure it works.

**Comment by AliveDevil** [comment]
Seeing this as well (on 8.5.0)

Binlog: [msbuild.zip](https://github.com/ikvmnet/ikvm/files/11486135/msbuild.zip)

**Comment by martin-honnen** [comment]
I still get errors when trying to to build in VS. However, when I unload the projects in VS and go to the command line/powershell and do first a `dotnet clean` and then a `dotnet build` there, those seem to run through fine. Also `dotnet run --framework net6.0` then for the `IKVM840UseJavaFromConsoleAppTest1` works and outputs e.g. `Hello World: .NET 6.0.16, Java 1.8.0`.
I am not sure what makes the difference between VS building and the command line.

**Comment by trungnt2910** [comment]
> So, with msbuild /restore this works, waiting and then issuing msbuild (without restore) brings this issue up (when using IKVM.NET.Sdk).

This is the working workaround for 8.6.4.

First, run `dotnet msbuild /restore` on the command line.
After that, building and everything should work like normal.

**Comment by martin-honnen** [comment]
I tried to upgrade that test solution to IKVM 8.8.1 (and .NET 6 and .NET 8 as the target frameworks), I got it building and running from the command line within 20 minutes; it usually helps to remove anything in the various projects' bin\Release\* and bin\Debug\* by hand with e.g. `del -r bin\Release\*`. 
As far as I am concerned, you can close this.
