### ISSUE TITLE
IKVM.NET.Sdk trying to compile Java project gives error about java.util.Node although the Java code doesn't reference/import that class

### ISSUE THREAD

**Issue by martin-honnen** [ikvmnet/ikvm#287]
I have been trying to compile the Saxon HE 10.8 Java sources through `IKVM.NET.Sdk/8.4.5` but I end up with an error
```
1>MSBUILD : error compiler.err.cant.access: cannot access java.util.Node
1>MSBUILD : error compiler.err.cant.access:   bad class file: \\.ikvm\assembly\IKVM.Java__8.4.5.0__13235d27fcbfff58\classes\java\util\Node.class
1>MSBUILD : error compiler.err.cant.access:     unable to access file: File not found.
1>MSBUILD : error compiler.err.cant.access:     Please remove or make sure it appears in the correct subdirectory of the classpath.
```
that I think suggests somehow the build looks for `java.util.Node` although I don't think any source imports or references that class, I think `org.w3c.dom.Node` imported by some files through `import org.w3c.dom.*;` is what should be looked up by the build process.

Sample project is up at https://github.com/martin-honnen/SaxonHE108JavaIkvmSdkTest3.

This is not a regression of 8.4.5, I got similar errors with 8.4.4.

Nevertheless I hope you can somehow fix IKVM.NET.Sdk to allow compiling such projects.

**Comment by wasabii** [comment]
I have an idea of what this is now. I tracked down something similar when trying to rewrite the NIO classes on a branch a few weeks ago. There was one part of NIO that wasn't happy with the VFS path with a . At the beginning of the computer name.

I'm pushing a prerelease develop build with the path changed to not have a .

Well be a few hours until it all builds. But can you try it then?

**Comment by martin-honnen** [comment]
Might be too late in the evening for me to try today but I will have a look tomorrow.

**Comment by wasabii** [comment]
Fixed that issue in your sample project for me. Lots of other compiler errors, but at least that is gone.

**Comment by martin-honnen** [comment]
For me not:
```
1>C:\Users\marti\.nuget\packages\ikvm\8.4.5\buildTransitive\netstandard2.0\IKVM.Tasks.targets(31,9): warning : ikvmc (8.4.5+Branch.main.Sha.548430396151a2e5cb51fb319e15524bd601ace5)
1>C:\Users\marti\.nuget\packages\ikvm\8.4.5\buildTransitive\netstandard2.0\IKVM.Tasks.targets(31,9): warning : Copyright © 2023 Jeroen Frijters, Windward Studios, Jerome Haltom, Shad Storhaug
1>C:\Users\marti\.nuget\packages\ikvm\8.4.5\buildTransitive\netstandard2.0\IKVM.Tasks.targets(31,9): warning :
1>MSBUILD : error compiler.err.cant.access: cannot access java.util.Node
1>MSBUILD : error compiler.err.cant.access:   bad class file: \\.ikvm\assembly\IKVM.Java__8.4.5.0__13235d27fcbfff58\classes\java\util\Node.class
1>MSBUILD : error compiler.err.cant.access:     unable to access file: File not found.
1>MSBUILD : error compiler.err.cant.access:     Please remove or make sure it appears in the correct subdirectory of the classpath.
```

**Comment by wasabii** [comment]
Wrong version.

**Comment by martin-honnen** [comment]
Oddly I get that version output `ikvmc (8.4.5+Branch.main.Sha.548430396151a2e5cb51fb319e15524bd601ace5)` for a project having `<Project Sdk="IKVM.NET.Sdk/8.5.0-develop0690">`. I guess its the same problem I have with any release that it is never clear when my machine really has all the relevant files.
When I don't use the VS `build` menu but the command line `dotnet build` in the solution directory I get an error and a warning:
```
C:\Users\marti\.nuget\packages\ikvm\8.5.0-develop0690\buildTransitive\netstandard2.0\IKVM.Tasks.targets(33,9): warning : error IKVMC4005: Source file 'C:\Users\mart
i\source\repos\SaxonHE108JavaIkvmSdkTest3\SaxonHE108J\%(IkvmReferenceItem.Compile->'C:\Users\marti\source\repos\SaxonHE108JavaIkvmSdkTest3\SaxonHE108J\xml-resolver-
1.2.jar')' not found [C:\Users\marti\source\repos\SaxonHE108JavaIkvmSdkTest3\SaxonHE108J\SaxonHE108J.msbuildproj::TargetFramework=netcoreapp3.1]
C:\Users\marti\.nuget\packages\ikvm\8.5.0-develop0690\buildTransitive\netstandard2.0\IKVM.Tasks.targets(33,9): warning : Error: unable to find 'netstandard.dll'. [C
:\Users\marti\source\repos\SaxonHE108JavaIkvmSdkTest3\SaxonHE108J\SaxonHE108J.msbuildproj::TargetFramework=netcoreapp3.1]
```
The jar file is in the `dir C:\Users\marti\source\repos\SaxonHE108JavaIkvmSdkTest3\SaxonHE108J\xml-resolver-1.2.jar` shows it.
I don't know what to make of the `netstandard.dll` warning, where should that file be found?

**Comment by martin-honnen** [comment]
Or is that error message telling it is literally looking for a file path `C:\Users\marti\source\repos\SaxonHE108JavaIkvmSdkTest3\SaxonHE108J\%(IkvmReferenceItem.Compile->'C:\Users\marti\source\repos\SaxonHE108JavaIkvmSdkTest3\SaxonHE108J\xml-resolver-1.2.jar`?

**Comment by wasabii** [comment]
Welp, another bug that slipped into develop. Fixing.
