### ISSUE TITLE
IKVM.Net.SDK fails to compile lambda expression

### ISSUE THREAD

**Issue by mrjfalk** [ikvmnet/ikvm#303]
Trying out the IKVM.NET.SDK (version 8.4.5) I get an error when trying to compile any `FunctionalInterface`, e.g. `Runnable` as a lambda expression, it fails with the following exception for me:

> com.sun.tools.javac.code.Symbol$CompletionFailure: class file for java.lang.invoke.MethodHandles$Lookup not found
> error MSB4181: The "IkvmJavaCompiler" task returned false but did not log an error. [<path>\lambda\lambda.msbuildproj::TargetFramework=net461]

THe bug can reproduced with only two files; the `lambda.msbuildproj`:

```xml
<Project Sdk="IKVM.NET.Sdk/8.4.5">

  <PropertyGroup>
    <TargetFrameworks>net461;netcoreapp3.1</TargetFrameworks>
  </PropertyGroup>
</Project>
```

And a very simple class `LambdaBug.java` returning a lambda from a static method:

```
package sample;

import java.lang.Runnable;

public class LambdaBug {

    public static Runnable create() {
        return () -> { };
    }
}
```

**Comment by wasabii** [comment]
So this is an interesting problem.... and I seem to remember having come across something like it in the past. Going to require pulling stuff up in a debugger I think.

Explanation:

IKVM makes the .class files for the BCL available to the compiler within the VFS. That is, the fake magic file system under \.ikvm\assembly\IKVM_Java__\classes\java\lang\invoke\MethodHandles$Lookup.class. And these files are generated in memory on demand.

Going to need to dig into the code at runtime and figure out whether there's something wrong with that file. Either it doesn't exist (VFS leaves it out for some reason), or there's something else wrong.

**Comment by wasabii** [comment]
Going to suggest this gets reattempted in the latest version of IKVM. Recent changes to NIO to support VFS paths may resolve the issue. But, if not, please reopen.

**Comment by mrjfalk** [comment]
Can confirm that it works in 8.6.2.
