### ISSUE TITLE
Handle Windows named pipes on .Net Framework

### ISSUE THREAD

**Issue by AliveDevil** [ikvmnet/ikvm#314]
Trying to connect to e.g. `\\.\pipe\openssh-ssh-agent` on Windows in .net framework fails, as FileStream doesn't work on `"\\.pipe`-streams.

Context: iterate-ch/cyberduck#12895, which lead to https://github.com/iterate-ch/ikvm/compare/8.0.312.b07-2..8.0.312.b07-7

**Comment by wasabii** [comment]
So I think the best way to go about this one is to put work into getting the jio native library working. That'll solve the issue, and be good in other ways. We should be on the path for getting that done at this point.

**Comment by wasabii** [comment]
I think this is probably fixed at this point since all our NIO stuff is using the Native OpenJDK code. Or at least as fixed as it is in normal JDK.
