### ISSUE TITLE
Image (JRE/JDK) missing ikvm.properties file in bin/

### ISSUE THREAD

**Issue by base553** [ikvmnet/ikvm#315]
![image](https://user-images.githubusercontent.com/63432702/234798282-a976335f-669a-44f8-b9b4-5d524f998a19.png)

it tell me cant find the “D:\env\IKVM-8.3.3-net461-win7-x64\bin\ikvm\lib\currency.data" 

but I find it at "D:\env\IKVM-8.3.3-net461-win7-x64\lib\currency.data" 

maybe  "javac.exe" had some bug ?

**Comment by base553** [comment]
file path has some bug ? and i had tried the lastest one , it also tell me cant find . but if i create the dic and copy "lib" to "ikvm/lib".
it will work normally.

**Comment by wasabii** [comment]
Looks like the image packages are missing a file, ikvm.properties, in the bin directory. Not sure how this got left off.

Either way, you can fix this by creating a file named ikvm.properties, in the bin/ directory, and putting a single line into it:

`ikvm.home=..`

**Comment by wasabii** [comment]
Since we're so close to 8.6, and this problem was resolved in 8.6, I'm not going to worry about applying it to 8.5 at this time.

**Comment by base553** [comment]
ok,let me try it . thanks a lot.
