### ISSUE TITLE
IKVM.NET.Sdk: Is there a way to add Java resources?

### ISSUE THREAD

**Issue by dermot-hardy** [ikvmnet/ikvm#325]
I've tried using `IKVM.NET.Sdk` and I have to say it's fantastic.  I do have a question though.  How do you add a Java resource?

For example I tried to implement an SLF4J Provider that uses a .NET logger.  Here is the `.msbuildproj` file:

    <Project Sdk="IKVM.NET.Sdk/8.5.0">
      <PropertyGroup>
        <TargetFramework>netcoreapp3.1</TargetFramework>
      </PropertyGroup>
      <ItemGroup>
        <PackageReference Include="IKVM.Maven.Sdk" Version="1.4.1" />
        <MavenReference Include="slf4j-api">
          <GroupId>org.slf4j</GroupId>
          <ArtifactId>slf4j-api</ArtifactId>
          <Version>2.0.7</Version>
        </MavenReference>
      </ItemGroup>
    </Project>

It compiles the Java code that implements the slf4j interfaces just fine, but I don't know how to add the `META-INF\services\org.slf4j.spi.SLF4JServiceProvider` resource.  I presume I could build it into a jar and reference that using another `<MavenReference>` but that seems a hacky.  Is there a cleaner way to do it?

**Comment by wasabii** [comment]
Resource ItemGroup. I don't think I have any documentation on that. But it shouldn't be too hard to see how it works.

**Comment by wasabii** [comment]
JavaResource I mean. Check the source code for IKVM.Java. It uses it.

**Comment by dermot-hardy** [comment]
Fantastic thanks.
