### ISSUE TITLE
Could not locate ikvm.home when establishing VFS.

### ISSUE THREAD

**Issue by podlodkin** [ikvmnet/ikvm#358]
**File:** 
IKVM.Runtime\JVM.Properties.cs

**Function:** 
GetHomePath

**Code:**
` var rootPath = Path.GetDirectoryName(typeof(JVM).Assembly.Location);`
returns “shadow-copying” directory path. 
For example,
`C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\root\c027dea8\2d30b62c\assembly\dl3\e775bdb1\00e9c755_4899d901`

There is no “ikvm” catalogue and as the result we have an error:

_Could not locate ikvm.home when establishing VFS._

Rather than calling typeof(JVM).Assembly.Location, you can call typeof(JVM).Assembly.CodeBase which gives you the original install directory (which contains ikvm folder).

P.s. This is not a constant error - it depends on environmental configuration (VS, IIS, ...).

**Comment by AliveDevil** [comment]
Only available/usable on .NET Framework (as in your case).

> Assembly.CodeBase and Assembly.EscapedCodeBase are only included for .NET Framework compatibility. Use Assembly.Location.

[Assembly.CodeBase Property](https://learn.microsoft.com/en-us/dotnet/api/system.reflection.assembly.codebase?view=net-6.0)


> **Exceptions**
> NotImplementedException
> .NET Core and .NET 5+ only: In all cases.

[Exceptions](https://learn.microsoft.com/en-us/dotnet/api/system.reflection.assembly.codebase?view=netcore-3.1#exceptions)

For .NET Core this won't work, at al.

**Comment by podlodkin** [comment]
> For .NET Core this won't work, at al.
Maybe we need different rootPath algorithms for .net core and .net framework.
Actual algorithm doesn't work for .net 4.7.

**Comment by AliveDevil** [comment]
Shadow-Copying is a nightmare, and may or may not work (experimentally) in .NET Core as well.

https://github.com/dotnet/aspnetcore/issues/47465

**Comment by podlodkin** [comment]
Maybe we can optionally use an environmental parameter (as IKVM_PATH).

**Comment by wasabii** [comment]
We'll just have it read out of ConfigurationManager at a higher priority.
