### ISSUE TITLE
java.lang.NoSuchMethodError: java.nio.FloatBuffer.flip()Ljava.nio.FloatBuffer

### ISSUE THREAD

**Issue by Zegute** [ikvmnet/ikvm#365]
it return _Unhandled exception. java.lang.NoSuchMethodError: java.nio.FloatBuffer.flip()Ljava.nio.FloatBuffer;_ when method flip called

**Comment by wasabii** [comment]
Going to need more information about this. There's no indication about what software is being used or anything.

**Comment by wasabii** [comment]
Ahh. So, there is a ()Ljava.nio.FloatBuffer version of flip() in JDK9. Guessing you're trying to run a JDK9 JAR file. We do not yet support anything beyond JDK8.

Going to close this for now.

#120
