### ISSUE TITLE
Building Develop branch fails when specifying Enabled*Runtimes

### ISSUE THREAD

**Issue by TheLastRar** [ikvmnet/ikvm#374]
Attempting to build commit 26da52f9db5540bc712a76d6e811fd997ddd1942

This is something I suspect was caused by the unpack branch merge, as I was able to build before that merged

Attempting to build the develop branch with `/p:EnabledRuntimes=win7-x64 /p:EnabledToolRuntimes=win7-x64 /p:EnabledImageRuntimes=win7-x64` fails

I don't have the SDKs for platforms other than windows installed, hence why I've specified just win7-x64, yet the build appears to be trying to build for other platforms regardless.

`msbuild IKVM.dist.msbuildproj /m /bl /p:BuildInParallel=true /p:CreateHardLinksForAdditionalFilesIfPossible=true /p:CreateHardLinksForCopyAdditionalFilesIfPossible=true /p:CreateHardLinksForCopyFilesToOutputDirectoryIfPossible=true /p:CreateHardLinksForCopyLocalIfPossible=true /p:CreateHardLinksForPublishFilesIfPossible=true /p:EnabledRuntimes=win7-x64 /p:EnabledToolRuntimes=win7-x64 /p:EnabledImageRuntimes=win7-x64 -fileLogger`

Attached both the binlog and txt log
[ikvm.zip](https://github.com/ikvmnet/ikvm/files/11925737/ikvm.zip)

**Comment by TheLastRar** [comment]
That was pretty quick, thanks

**Comment by wasabii** [comment]
Can confirm was resposible for long build times on CI too. Probably looping into projects multiple times where it shouldn't have,
