### ISSUE TITLE
VB.NET which used lib pdfbox.dll and ivkm.runtime.dll

### ISSUE THREAD

**Issue by SamsonJathanna** [ikvmnet/ikvm#382]
Guys, I had written a small code in VB.NET which used lib pdfbox.dll and ivkm. The application was working perfectly well till i upgraded to visual studio 2022. After upgrading to visual studio 2022, my vb.form was having problem so i recreated the form and kept the functional code same. It is supposed to nename the PDF file after reading contents inside it.

the .dll's used are as IKVM.OpenJDK.Core.dll IKVM.OpenJDK.Text.dll IKVM.OpenJDK.Util.dll IKVM.Runtime.dll  pdfbox-1.8.9.dll  commons-logging.dll fontbox-1.8.9.dll

![image](https://github.com/ikvmnet/ikvm/assets/139523982/40bf48de-2977-4b38-9502-cb9d946487a8)
![image](https://github.com/ikvmnet/ikvm/assets/139523982/9a717425-816f-4d0a-a295-136cc88a555b)

**Comment by wasabii** [comment]
There's a bit to unpack here.

We (this project) has nothing to do with the IKVM.OpenJDK.* assemblies released by Jeroen 10 years ago. We didn't release them, we don't support them, etc. The best I can do is comment on their history.

If you want to use the new modern IKVM package, the way to do so is to install the IKVM NuGet package in a modern SDK-style .NET project, and use IkvmReference or MavenReference, as mentioned in the README.

**Comment by wasabii** [comment]
Closing this as I believe the original question was answered.
