### ISSUE TITLE
IKVM-8.5.0-tools-netcoreapp3.1-win7-x64

### ISSUE THREAD

**Issue by acmelinkdotnet** [ikvmnet/ikvm#394]
*** INTERNAL COMPILER ERROR ***

PLEASE FILE A BUG REPORT FOR IKVM.NET WHEN YOU SEE THIS MESSAGE

IKVM.Tools.Importer, Version=8.5.0.0, Culture=neutral, PublicKeyToken=13235d27fcbfff58
C:\Accessbox\IKVM-8.5.0-tools-netcoreapp3.1-win7-x64\
3.1.32 64-bit

System.IO.FileNotFoundException: netstandard
   at IKVM.Reflection.Universe.Load(String refname, Module requestingModule, Boolean throwOnError) in C:\work\ikvm\src\IKVM.Reflection\Universe.cs:line 547
   at IKVM.Tools.Importer.AssemblyResolver.Init(Universe universe, Boolean nostdlib, IList`1 references, IList`1 userLibPaths) in C:\work\ikvm\src\IKVM.Tools.Importer\AssemblyResolver.cs:line 96
   at IKVM.Tools.Importer.IkvmImporterInternal.Compile(String[] args) in C:\work\ikvm\src\IKVM.Tools.Importer\IkvmImporterInternal.cs:line 179
   at IKVM.Tools.Importer.IkvmImporterInternal.Execute(String[] args) in C:\work\ikvm\src\IKVM.Tools.Importer\IkvmImporterInternal.cs:line 112

C:\Accessbox\IKVM-8.5.0-tools-netcoreapp3.1-win7-x64>

**Comment by wasabii** [comment]
I don't see any information about what command line arguments you were passing nor what you were trying to do.

**Comment by acmelinkdotnet** [comment]
Hello,
Sorry for the late reply.
The full command executed and error is below.
C:\Accessbox\IKVM-8.5.0-tools-netcoreapp3.1-win7-x64>ikvmc C:\Accessbox\prowide-iso20022-SRU2022-9.3.7\prowide-iso20022-SRU2022-9.3.7\pw-iso20022-SRU2022-9.3.7.jarIKVM.Tools.Importer (8.5.0+Branch.main.Sha.72775a3217fb86e495108d73dd03b4b1a9080e9d)Copyright c 2023 Jeroen Frijters, Windward Studios, Jerome Haltom, Shad Storhaug

*** INTERNAL COMPILER ERROR ***
PLEASE FILE A BUG REPORT FOR IKVM.NET WHEN YOU SEE THIS MESSAGE
IKVM.Tools.Importer, Version=8.5.0.0, Culture=neutral, PublicKeyToken=13235d27fcbfff58C:\Accessbox\IKVM-8.5.0-tools-netcoreapp3.1-win7-x64\3.1.32 64-bit
System.IO.FileNotFoundException: netstandard   at IKVM.Reflection.Universe.Load(String refname, Module requestingModule, Boolean throwOnError) in C:\work\ikvm\src\IKVM.Reflection\Universe.cs:line 547   at IKVM.Tools.Importer.AssemblyResolver.Init(Universe universe, Boolean nostdlib, IList`1 references, IList`1 userLibPaths) in C:\work\ikvm\src\IKVM.Tools.Importer\AssemblyResolver.cs:line 96   at IKVM.Tools.Importer.IkvmImporterInternal.Compile(String[] args) in C:\work\ikvm\src\IKVM.Tools.Importer\IkvmImporterInternal.cs:line 179   at IKVM.Tools.Importer.IkvmImporterInternal.Execute(String[] args) in C:\work\ikvm\src\IKVM.Tools.Importer\IkvmImporterInternal.cs:line 112

Regards
    On Tuesday, July 25, 2023 at 04:46:38 PM GMT+1, Jerome Haltom ***@***.***> wrote:  
 
 


I don't see any information about what command line arguments you were passing nor what you were trying to do.

**Comment by wasabii** [comment]
So, you'll need to pass ikvmc a -reference argument for every assembly that it would expect to link to for your target platform of choice. That would be the entire contents of the .NET Core 3.1 SDK. And, you need to specify -runtime to point to the version of IKVM.Runtime you want the resulting assembly to link to.

This is all very complicated.

Which is why we recommend using the SDK support: either through MavenReference or IkvmReference, as descsribed in the README.

**Comment by wasabii** [comment]
No follow up, and I believe this question has been answered.
