### ISSUE TITLE
How to point to internal maven repositories to resolve depencies?

### ISSUE THREAD

**Issue by askids** [ikvmnet/ikvm#395]
hi,

For resolving java package dependencies, documentation mentions not to copy the jar, but to use maven reference. Our builds are run in environment, which has no access to internet. So there is a local copy of the Nuget repos, Maven repos etc maintained by a central team. For dotnet packages, we can provide custom Nuget config files to resolve the feeds. So now, when we use maven reference, how do we provide the internal maven repository URL to resolve the dependencies? 

Thanks!

**Comment by wasabii** [comment]
There are a number of MSBuild properties you can set on the project or globally:

```
        <MavenDefaultRepositories Condition=" '$(MavenDefaultRepositories)' == '' ">central=https://repo1.maven.org/maven2/</MavenDefaultRepositories>
        <MavenAdditionalRepositories Condition=" '$(MavenAdditionalRepositories)' == '' "></MavenAdditionalRepositories>
        <MavenRepositories Condition=" '$(MavenRepositories)' == '' ">$(MavenDefaultRepositories);$(MavenAdditionalRepositories)</MavenRepositories>
```

Makes most sense to add additional repositories to MavenAdditionalRepositories, since that gets merged into the total set.

**Comment by wasabii** [comment]
Assuming this question is answered and closing.
