### ISSUE TITLE
Reduce garbage collection?

### ISSUE THREAD

**Issue by TechInterMezzo** [ikvmnet/ikvm#396]
Is it possible to influence how the memory allocation or garbage collection in IKVM and converted libraries work?
I am calling a long running method from converted java library and it seems to do a lot of garbage collection which slows down the application.

**Comment by wasabii** [comment]
So, it is just .NET. so what your really looking for is how to influence the. Net runtime along those lines.

Which the MS documentation is going to cover.

**Comment by TechInterMezzo** [comment]
Okay, thank you.
