### ISSUE TITLE
OpenJDK 8u252 Upgrade

### ISSUE THREAD

**Issue by AliveDevil** [ikvmnet/ikvm#397]
Complete changeset: https://github.com/openjdk/jdk8u/compare/jdk8u152-b16..jdk8u252-ga

Noticable changes:
// to be filled out

- [ ] Change openjdk/ commit ID
- [ ] Validate local forks for changes.
  - [ ] Check `java.io.FileDescriptor` for changes. Numerous local changes.
  - [ ] Check `sun.misc.VM` for changes.
  - [ ] Check `sun.nio.ch` for changes. Large fork.
  - [ ] Check `sun.nio.fs` for changes. Large fork.
  - [ ] java.security file may have been altered, fix all the local copies (multiple per arch/image)
  - [ ] Check jdk/make/GenerateClasses.gmk for changes
  - [ ] Check `sun.reflect` for changes
- [ ] Port SharedSecrets.java

**Comment by AliveDevil** [comment]
Reason for not going any further than 252: The amount of changes triples after that.

**Comment by wasabii** [comment]
Closing in favor of 8u725.
