### ISSUE TITLE
Licence clarification

### ISSUE THREAD

**Issue by xrkatsenos** [ikvmnet/ikvm#398]
Hello,

We are developing applications using C# and we use ikvm 8.2

During a recent scan of the ikvm source code, I came across references to 
    Line 2874 - GLX Public License v1.0
    Line 3069 - CID FONT CODE PUBLIC LICENSE (Version 1.0 (3/31/99))("License")
    Line 2427 - exception to GPL

We have identified the above licenses in this file: https://github.com/ikvm-revived/ikvm/blob/8.2.0/THIRD_PARTY_README

This discovery has raised concerns about the potential impact on the licensing of our software.
I would be grateful if you could provide insights into whether using ikvm in our applications would subject them to the above licenses.

Additionally, we would like to know if the source code of the third parties is under the above mentioned licenses is included in the final provided software.

Thanks in advance.

**Comment by wasabii** [comment]
The THIRD_PARTY_README is ultimately a product of the OpenJDK project, and refers to code within that project, which is part of the OpenJDK source distribution. Our entire base class library is sourced from the OpenJDK project, and thus may be covered by one or more of the libraries in this file. That said, the vast majority of OpenJDK code is licensed GPLv2+CPE.

I could not tell you with certainty which parts of the OpenJDK project are covered by which licenses represented in this file. I can tell you which part of the OpenJDK is consumed by IKVM. And that's almost the entirety of the class library, and soon to be many of the native JNI backend components. We also bundle a good deal of the lib/ directory from the OpenJDK distribution, which I think so far contains some images, but not any fonts, given the state of our AWT implementation. We'll probably add the fonts at a future point. I'm not sure though whether those would be the CID covered fonts or not, however.

We don't redistribute or use any of the components of the build system of OpenJDK though.

**Comment by wasabii** [comment]
I believe this has been answered, and no follow up, so closing.
