### ISSUE TITLE
System.BadImageFormatException

### ISSUE THREAD

**Issue by chenjing1294** [ikvmnet/ikvm#407]
```
System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (0x8007000B)
```
Works fine on Windows, fails on Linux 22.04 x64

**Comment by wasabii** [comment]
There isn't enough information here to have any idea what is going on.

**Comment by wasabii** [comment]
No response. Nothing I can really do here. Don't know anything about what the user is doing. Reopen if still present.
