### ISSUE TITLE
Possible to hide ikvm/ikvm.properties?

### ISSUE THREAD

**Issue by giulianob** [ikvmnet/ikvm#408]
Hello,

Any project that references IKVM (even transitively) ends up getting the ikvm/ikvm.properties external files added to the project tree. Is there any way to hide those?

**Comment by wasabii** [comment]
Not presently, no. IKVM needs a number of local files present to form a complete JRE environment. The ikvm.properties file directs the runtime to where those files live, which by default is in ikvm/{rid}, where RID is auto detected from the current runtime environment.

**Comment by wasabii** [comment]
Going to close this since there's not really a bug or anything.
