### ISSUE TITLE
Can't work on Visual Studio 2022 arm version

### ISSUE THREAD

**Issue by happywjh** [ikvmnet/ikvm#419]
Use MavenReference in project , can't work on Visual Studio 2022 arm version. <img width="809" alt="image" src="https://github.com/ikvmnet/ikvm/assets/1041149/d6b9f0c7-5fbe-4680-bac5-9269d402d52d">
<img width="792" alt="image" src="https://github.com/ikvmnet/ikvm/assets/1041149/12d0d628-f71e-4e08-a75d-5b2248c36f9a">

**Comment by wasabii** [comment]
This is correct. No support for the SDK on ARM64 for Windows as of yet.

#197

**Comment by wasabii** [comment]
Duplicate #197. Which is being half-fixed in 8.7, with support for SDK tools on Core (.NET6>). No Framework support yet. But, closing this bug as duplicate anyways.

For framework: #432
