### ISSUE TITLE
Unable to install IKVM 8.7.1 on .NET Framework 4.8 or 4.7.2

### ISSUE THREAD

**Issue by BiologyTools** [ikvmnet/ikvm#445]
While trying to install IKVM 8.7.1 via NuGet on a new .NET Framework project I get the following error:
```Unable to find a version of 'Mono.Posix' that is compatible with 'IKVM 8.7.1 constraint: Mono.Posix (>= 7.1.0-final.1.21458.1)'.```	
Can you figure out what could be causing this?

Best, Erik

**Comment by wasabii** [comment]
Nope. That's not a new dependency. Been around for a few major versions now.

Not trying to do this from behind some sort of NuGet proxy that removes certain packages, are you?

**Comment by BiologyTools** [comment]
I've run into this issue before but that was many versions ago and was able to just install an older version then the error went away. No I'm not behind any proxy that I am aware of. I'm trying to get BioFormats working on .NET 4.8 now.

**Comment by NightOwl888** [comment]
Last I checked, those NuGet version constraints are not compatible with prerelease versions (they don't correctly determine which version is higher).

**Comment by wasabii** [comment]
Maybe it's not an SDK style project?

**Comment by BiologyTools** [comment]
I can install a pre-release just fine but trying to install a non-prerelease gives me that error. Yes it is a non-sdk style .NET Framework project.

**Comment by wasabii** [comment]
We do not support non SDK style projects at all.

**Comment by BiologyTools** [comment]
How would one then use IKVM on older projects? Is there an older version of IKVM which supported non-SDK projects? Asking this since the Bioformats page will soon have C# instructions with IKVM so would be nice to know if there is any workaround for non-SDK style projects.

**Comment by wasabii** [comment]
You would convert the project to SDK style. That's it. There is no version of IKVM ever released that supported non-SDK style projects, because prior to ours, there was no version of IKVM released that had any build integration at all.

**Comment by BiologyTools** [comment]
Because what I've done with non-SDK style projects is use the old Bioformats.NET package which uses IKVM 8.1.5717.0 and it works fine. So should I just keep using the old package with IKVM 8.1.5717.0?

**Comment by wasabii** [comment]
You should convert your project to SDK style. Everybody should.

**Comment by BiologyTools** [comment]
Ok I will make sure that users know to just use SDK style projects for Bioformats once their website is updated.

**Comment by wasabii** [comment]
The reasoning here for us is pretty simple: our MSBuild integration (to build assemblies on the fly, export JARs, copy runtime assets, etc) is very, very complex, and relies on targets, properties, items, order of operations, and all sort of subtle differences between the two project types. And it's just me working on it. There's no way I could justify putting the time into building a second copy of most of that, and maintaining and testing it. To support a format MS recommends people away from anyways, and to which there is almost zero reason to not do so. .NET Framework projects work fine in SDK-style.

The only reason you might not be able to do SDK-style projects is if you're using some old version of VS, like >5 years old, or some weird third-party extensions that force it.

**Comment by BiologyTools** [comment]
Thank you for the further information. I will let the Bioformats team know only SDK-style projects are supported and that any older projects should migrate, as instructed by Microsoft. I am excited to see IKVM in the Bioformats developer documentation page https://bio-formats.readthedocs.io/en/latest/developers/index.html soon. Your work will help a lot of scientists out. Keep up the amazing work.

**Comment by NightOwl888** [comment]
> The only reason you might not be able to do SDK-style projects is if you're using some old version of VS, like >5 years old. Or a very, very legacy project type of some kind (classic ASP.NET might be an issue, etc). And even there there's going to be a workaround. Like move IKVM usage into a seperate project, to which you add a reference.

There are some other project types that don't support SDK style projects AFAIK:

1. Visual Studio Extensions (code analyzers, code generators, VS tools, etc).
2. Xamarin (Android, iOS, Mac) projects. However, these will be retired in 2024.
3. ASP.NET website projects (which don't even have a project file).

There are probably other projects I am unaware of that don't have an upgrade path, as well.

I get that it doesn't make sense to maintain a project formats for non-SDK projects for `MavenReference` and `IkvmReference`, since they are mainly legacy projects, anyway. But I still think it makes sense to make an easier-to-use command line tool so there is an option for those build tools (and any other oddball build tool that can execute a command in the console). That is, something as simple to use as `dotnet build`.
