### ISSUE TITLE
[8.7.1] System.NullReferenceException

### ISSUE THREAD

**Issue by s922197** [ikvmnet/ikvm#459]
Hi,
i have download ikvmc for net472 in windows (x64) package.

I had run below command in cmd console and got error message.
ikvmc -target:library -out:TEST.dll -assembly:TEST TEST.jar libs\*.jar -privatepackage:TEST

*** INTERNAL COMPILER ERROR ***

PLEASE FILE A BUG REPORT FOR IKVM.NET WHEN YOU SEE THIS MESSAGE

IKVM.Tools.Importer, Version=8.7.1.0, Culture=neutral, PublicKeyToken=13235d27fcbfff58
C:\Windows\Microsoft.NET\Framework64\v4.0.30319\
4.0.30319.42000 64-bit

System.NullReferenceException: 並未將物件參考設定為物件的執行個體。
   於 IKVM.Runtime.AttributeHelper.GetEditorBrowsableNever() 於 /_/src/IKVM.Runtime/AttributeHelper.cs: 行 402
   於 IKVM.Runtime.RuntimeByteCodeJavaType.JavaTypeImpl.AnnotationBuilder.Link() 於 /_/src/IKVM.Runtime/RuntimeByteCodeJavaType.JavaTypeImpl.cs: 行 1554
   於 IKVM.Runtime.RuntimeByteCodeJavaType.JavaTypeImpl.AnnotationBuilder.MakeCustomAttributeBuilder(RuntimeClassLoader loader, Object annotation) 於 /_/src/IKVM.Runtime/RuntimeByteCodeJavaType.JavaTypeImpl.cs: 行 1844
   於 IKVM.Runtime.RuntimeByteCodeJavaType.JavaTypeImpl.AnnotationBuilder.Apply(RuntimeClassLoader loader, MethodBuilder mb, Object annotation) 於 /_/src/IKVM.Runtime/RuntimeByteCodeJavaType.JavaTypeImpl.cs: 行 1858
   於 IKVM.Runtime.RuntimeByteCodeJavaType.FinishContext.FinishImpl() 於 /_/src/IKVM.Runtime/RuntimeByteCodeJavaType.FinishContext.cs: 行 677
   於 IKVM.Runtime.RuntimeByteCodeJavaType.JavaTypeImpl.FinishCore() 於 /_/src/IKVM.Runtime/RuntimeByteCodeJavaType.JavaTypeImpl.cs: 行 1285
   於 IKVM.Runtime.RuntimeByteCodeJavaType.JavaTypeImpl.Finish() 於 /_/src/IKVM.Runtime/RuntimeByteCodeJavaType.JavaTypeImpl.cs: 行 1206
   於 IKVM.Tools.Importer.RuntimeImportByteCodeJavaType.Finish() 於 /_/src/IKVM.Tools.Importer/RuntimeImportByteCodeJavaType.cs: 行 116
   於 IKVM.Runtime.RuntimeByteCodeJavaType.JavaTypeImpl.Finish() 於 /_/src/IKVM.Runtime/RuntimeByteCodeJavaType.JavaTypeImpl.cs: 行 1152
   於 IKVM.Tools.Importer.RuntimeImportByteCodeJavaType.Finish() 於 /_/src/IKVM.Tools.Importer/RuntimeImportByteCodeJavaType.cs: 行 116
   於 IKVM.Runtime.DynamicClassLoader.FinishAll() 於 /_/src/IKVM.Runtime/DynamicClassLoader.cs: 行 412
   於 IKVM.Tools.Importer.CompilerClassLoader.Compile(RuntimeContext context, StaticCompiler compiler, String runtimeAssembly, List`1 optionsList) 於 /_/src/IKVM.Tools.Importer/CompilerClassLoader.cs: 行 2547
   於 IKVM.Tools.Importer.IkvmImporterInternal.Compile(String[] args) 於 /_/src/IKVM.Tools.Importer/IkvmImporterInternal.cs: 行 196
   於 IKVM.Tools.Importer.IkvmImporterInternal.Execute(String[] args) 於 /_/src/IKVM.Tools.Importer/IkvmImporterInternal.cs: 行 111

**Comment by wasabii** [comment]
Same issue as https://github.com/ikvmnet/ikvm/issues/405
