### ISSUE TITLE
The target "ResolvePackageDependenciesForBuild" does not exist in the project

### ISSUE THREAD

**Issue by amjathrahman** [ikvmnet/ikvm#470]
Hi Team,

I'm getting the below error while trying to create a dll from jar file using the IKVM package version 8.7.3.

Error Details:
.nuget\packages\ikvm.msbuild\8.7.3\buildTransitive\IKVM.MSBuild.targets(37,47): error MSB4057: The target "ResolvePackageDependenciesForBuild" does not exist in the project.

Steps followed:
1. Added the following Nuget reference to project IKVM, IKVM.Image.JRE, IKVM.Image.JDK.
2. Added Item group reference as below
```
  <ItemGroup>
  <PackageReference Include="IKVM" Version="8.7.3" />
</ItemGroup>

<ItemGroup>
  <IkvmReference Include="C:\JavaCode\HelloWorld.jar" />
</ItemGroup>
```
3. Build the application (Winforms, 4.8 framework)

please help me with this issue, I'm new to this version of IKVM. previously I used to user older version of IKVMC.
With Thanks
Amjath

**Comment by wasabii** [comment]
Is it an SDK style project?

**Comment by amjathrahman** [comment]
I need to create a new dll from JT400 jar version 20, If I use IKVMC then it uses the lower version of Java because that TLS version was sent as 1.0 in the client hello. So I want to create dll using a newer version of IKVM. can you please help me on this?

**Comment by wasabii** [comment]
Is that separate question? You didn't answer the first...

**Comment by amjathrahman** [comment]
Same Question... It's not SDK style project, It's just a dll reference project. Basically, I need a dll from the Jar file.

**Comment by wasabii** [comment]
https://github.com/ikvmnet/ikvm?tab=readme-ov-file#support

**Comment by wasabii** [comment]
Closing since project isn't an SDK project, and we only support SDK projects. If there is a seperate question.... which I cannot tell.... open a new issue with that.
