### ISSUE TITLE
java.lang.NoSuchMethodError thrown while calling a method

### ISSUE THREAD

**Issue by ubythulla** [ikvmnet/ikvm#499]
I added the jars directly to the dot net project and added ikvm reference in the csproj file as like below

```
<ItemGroup>
    <IkvmReference Include="Main.jar">
      <AssemblyName>Main</AssemblyName>
      <AssemblyVersion>2.5</AssemblyVersion>
      <AssemblyFileVersion>2.5.0.0</AssemblyFileVersion>
    </IkvmReference>
  </ItemGroup>

```

I can able to access the java method which comes from the Main.jar in the C# without any error as like below
```
common.net.util.ConvertUtils.convertFromEntityList(rules,  seqState);
```

During the run time of application I am getting the error and the cache file also contains the same error.

```ERROR: warning IKVMC0117: Emitted java.lang.NoSuchMethodError in "common.net.util.ConvertUtils.convertFromEntityList(Ljava.util.List;Lcommon.net.util.ConvertUtils$SequenceState;)Ljava.util.List;"```

_Originally posted by @ubythulla in https://github.com/ikvmnet/ikvm/issues/431#issuecomment-2009332871_

**Comment by wasabii** [comment]
Seems to be a missing method. Did you forget to add a dependency?

**Comment by ubythulla** [comment]
The method **common.net.util.ConvertUtils.convertFromEntityList(rules,  seqState)**, which I am accessing is available in the **Main.jar** and I have added the reference in the csproj file
```<ItemGroup>
    <IkvmReference Include="Main.jar">
      <AssemblyName>Main</AssemblyName>
      <AssemblyVersion>2.5</AssemblyVersion>
      <AssemblyFileVersion>2.5.0.0</AssemblyFileVersion>
    </IkvmReference>
  </ItemGroup>```

Should I have to add any other dependency

**Comment by wasabii** [comment]
But what methods does that method call?

**Comment by ubythulla** [comment]
that method calls the below method from main2.jar
```common.codec.Types.AddEntryRequest.newSelcritEntryRequest(common.util.InetPrefix;common.util.InetPrefix,int a,int b,int c)```
 and I refered the Main2.jar in the reference section
```<IkvmReference Include="Main.jar">
      <AssemblyName>Main</AssemblyName>
      <AssemblyVersion>2.5</AssemblyVersion>
      <AssemblyFileVersion>2.5.0.0</AssemblyFileVersion>
     <Reference>Main2.jar<Reference>
    </IkvmReference>
  </ItemGroup>```

**Comment by wasabii** [comment]
And did you add a reference to Main2.jar?

**Comment by ubythulla** [comment]
added like this for main2.jar
``` 
   <IkvmReference Include="Main2.jar">
      <AssemblyName>Main2</AssemblyName>
      <AssemblyVersion>2.5</AssemblyVersion>
      <AssemblyFileVersion>2.5.0.0</AssemblyFileVersion>
    </IkvmReference>```

**Comment by ubythulla** [comment]
```common.net.util.ConvertUtils.convertFromEntityList(rules,  seqState)``` 
method internally calling 
`common.codec.Types.AddEntryRequest.newSelcritEntryRequest(common.util.InetPrefix;common.util.InetPrefix,int a,int b,int c)`

`package common.util.InetPrefix
public class InetPrefix 
{
}`
this class is used as the argument in the newSelcritEntryRequest

there is a child class from the different jar implements the common.util.InetPrefix
`package common.ssn.InetPrefix
public class InetPrefix extends common.util.InetPrefix
{
}`

there are two classes in the same name from different namespaces one is base and another one is child class and the method newSelcritEntryRequest having the parameter of base type where as ikvm is looking with the child type and throws method not found error.

```ERROR: warning IKVMC0117: Emitted java.lang.NoSuchMethodError in "common.codec.Types.AddEntryRequest.newSelcritEntryRequest(Lcommon.ssn.InetPrefix;Lcommon.ssn.InetPrefix)"```

```<ItemGroup>
    <IkvmReference Include="Main.jar">
      <AssemblyName>Main</AssemblyName>
      <AssemblyVersion>2.5</AssemblyVersion>
      <AssemblyFileVersion>2.5.0.0</AssemblyFileVersion>
 <Reference>Main2.jar;common.util.InetPrefix.jar <Reference>//added the 2 jar reference
    </IkvmReference>
  </ItemGroup>// this has the convertFromEntityList() method
<ItemGroup>
    <IkvmReference Include="Main2.jar">
      <AssemblyName>Main2</AssemblyName>
      <AssemblyVersion>2.5</AssemblyVersion>
      <AssemblyFileVersion>2.5.0.0</AssemblyFileVersion>
<Reference>common.util.InetPrefix.jar <Reference>//added base class param refrence jar
    </IkvmReference>
  </ItemGroup>// this has the newSelcritEntryRequest() method
 <IkvmReference Include="common.util.InetPrefix.jar">
      <AssemblyName>CommonUtil</AssemblyName>
      <AssemblyVersion>2.5</AssemblyVersion>
      <AssemblyFileVersion>2.5.0.0</AssemblyFileVersion>
    </IkvmReference>
  </ItemGroup>// this has the base param class
 <IkvmReference Include="common.ssn.InetPrefix.jar">
      <AssemblyName>CommonSSN</AssemblyName>
      <AssemblyVersion>2.5</AssemblyVersion>
      <AssemblyFileVersion>2.5.0.0</AssemblyFileVersion>
    </IkvmReference>
  </ItemGroup>//this has the child param class and other methods which required for the project hence added this reference. 
```

**Comment by wasabii** [comment]
I'll be honest here, I think you're just not being very careful with things. You have typos, and missing references in the example above.

**Comment by wasabii** [comment]
Been a while. Haven't seen a bug posted. Closing.
