### ISSUE TITLE
Got this issue when executed creation of jackcess

### ISSUE THREAD

**Issue by yuriycto** [ikvmnet/ikvm#504]
Executed this command
ikvmc -target:library -out:jackcess-4.0.5.dll jackcess-4.0.5.jar
Got following:

IKVM.Tools.Importer (8.8.0-pre.1+Branch.tags-8.8.0-pre.1.Sha.56a3f6fdc68c9d1675802e0818f35f736d4dad51)
Copyright c 2024 Jeroen Frijters, Windward Studios, Jerome Haltom, Shad Storhaug

Core library not found. Make sure the appropriate reference assemblies for the target environment are included.

*** INTERNAL COMPILER ERROR ***

PLEASE FILE A BUG REPORT FOR IKVM.NET WHEN YOU SEE THIS MESSAGE

IKVM.Tools.Importer, Version=8.8.0.0, Culture=neutral, PublicKeyToken=13235d27fcbfff58
C:\Windows\Microsoft.NET\Framework64\v4.0.30319\
4.0.30319.42000 64-bit

System.Exception: Exception of type 'System.Exception' was thrown.
   at IKVM.Tools.Importer.StaticCompiler.Init(Boolean nonDeterministicOutput, DebugMode debug, IList`1 libpaths) in /_/src/IKVM.Tools.Importer/StaticCompiler.cs:line 63
   at IKVM.Tools.Importer.IkvmImporterInternal.Compile(String[] args) in /_/src/IKVM.Tools.Importer/IkvmImporterInternal.cs:line 181
   at IKVM.Tools.Importer.IkvmImporterInternal.Execute(String[] args) in /_/src/IKVM.Tools.Importer/IkvmImporterInternal.cs:line 112

**Comment by wasabii** [comment]
Did you reference the core libraries?

An invocation of ikvmc requires that a -reference be specified for every assembly from the .NET platform you are targeting be referenced, as well as IKVM.Runtime and IKVM.Java.

IkvmReference simplifies this.

**Comment by yuriycto** [comment]
I resolved the problem. I didn't use proper versions of dll. After I've made sure that all IKVM dll were in the same version, problem resolved.
