### ISSUE TITLE
 error IKVMSDK0004: The IkvmReference maven$org.json:json:20080701 has invalid AssemblyName 'json' or AssemblyVersion '65535.0.0.0'. 

### ISSUE THREAD

**Issue by qcjxberin** [ikvmnet/ikvm#510]
<ItemGroup>
  <IkvmReference Include="wifi-sdk-1.0-SNAPSHOT-pg.jar" />
	<MavenReference Include="com.alibaba:fastjson" Version="1.2.47" />
  <MavenReference Include="slf4j-api">
 <GroupId>org.slf4j</GroupId>
 <ArtifactId>slf4j-api</ArtifactId>
 <Classifier></Classifier>
 <Version>1.7.30</Version>
 <Scope></Scope>
    <Exclusions></Exclusions>
	</MavenReference>
  <MavenReference Include="logback-classic">
 <GroupId>ch.qos.logback</GroupId>
 <ArtifactId>logback-classic</ArtifactId>
 <Classifier></Classifier>
 <Version>1.2.12</Version>
 <Scope></Scope>
    <Exclusions></Exclusions>
	</MavenReference>
  <MavenReference Include="org.eclipse.paho.client.mqttv3">
 <GroupId>org.eclipse.paho</GroupId>
 <ArtifactId>org.eclipse.paho.client.mqttv3</ArtifactId>
 <Classifier></Classifier>
 <Version>1.2.0</Version>
 <Scope></Scope>
    <Exclusions></Exclusions>
	</MavenReference>
</ItemGroup>

**Comment by qcjxberin** [comment]
When will it be updated?

**Comment by wasabii** [comment]
Can you check if this is resolved in 8.7.6?

**Comment by wasabii** [comment]
Well, I think it is.

**Comment by qcjxberin** [comment]
Yes
