### ISSUE TITLE
Can't Convert jar to dll

### ISSUE THREAD

**Issue by LxhSama** [ikvmnet/ikvm#517]
ikvmc -target:library wxbot1.1.jar have error 
IKVM.Tools.Importer (8.8.0+Branch.tags-8.8.0.Sha.0dcccd0af21487f20a29138a6a06948503cf8597)
Copyright ? 2024 Jeroen Frijters, Windward Studios, Jerome Haltom, Shad Storhaug

Core library not found. Make sure the appropriate reference assemblies for the target environment are included.

*** COMPILER ERROR ***

IKVM.Tools.Importer, Version=8.8.0.0, Culture=neutral, PublicKeyToken=13235d27fcbfff58
C:\Users\Administrator\Downloads\IKVM-8.8.0-bin-net8.0\ikvmc\net8.0\win-x64\
8.0.4 64-bit

System.Exception: Exception of type 'System.Exception' was thrown.
   at IKVM.Tools.Importer.StaticCompiler.Init(Boolean nonDeterministicOutput, DebugMode debug, IList`1 libpaths) in /_/src/IKVM.Tools.Importer/StaticCompiler.cs:line 72
   at IKVM.Tools.Importer.IkvmImporterInternal.Compile(String[] args) in /_/src/IKVM.Tools.Importer/IkvmImporterInternal.cs:line 178
   at IKVM.Tools.Importer.IkvmImporterInternal.Execute(String[] args) in /_/src/IKVM.Tools.Importer/IkvmImporterInternal.cs:line 112

**Comment by wasabii** [comment]
Did you "Make sure the appropriate reference assemblies for the target environment are included?"

**Comment by slxdy** [comment]
> Did you "Make sure the appropriate reference assemblies for the target environment are included?"

Can you clarify? What "core library" are we talking about? What "target environment" are we talking about? What are the "appropriate reference assemblies"? Please don't assume that everyone understands how your app works.

**Comment by LxhSama** [comment]
> Did you "Make sure the appropriate reference assemblies for the target environment are included?"

I compiled a utility library using Java 1.8, and then executed the command 'ikvmc -target:library wxbot1.1.jar' via the command line. I used the latest version 8.8 of IKVM.Tools. However, it threw the above error. The JAR file contains dependencies and can be executed correctly. I don't know if what you're saying is about needing me to include something in the Java package.

**Comment by wasabii** [comment]
Every assembly that is part of the target framework you are attempting to link to needs to be available to the compiler. That means -reference to everything like System.Private.CoreLib, System.Runtime, etc, out of the .NET SDK for the version you are targeting; or the appropriate reference assemblies for the version of .NET framework you are targeting, need to be specified on the command line.

**Comment by slxdy** [comment]
Can you add an argument like `-use-current-runtime` to make it automatically use the libraries that the compiler itself is using? Would make everything way easier

**Comment by wasabii** [comment]
No. You have to pass every assembly to the C# compiler, too.

Which the build system does. Which is why we recommend IkvmReference.

**Comment by LxhSama** [comment]
> No. You have to pass every assembly to the C# compiler, too. This has been required since .net core was introduced.
> 
> Which the build system does. Which is why we recommend IkvmReference.
Does that mean that the Tools approach cannot be used directly and instead, using IkvmReference is recommended?

**Comment by wasabii** [comment]
You can use the tools. They are just very hard to use. Same as the csharp compiler these days. 

IkvmReference is the only thing mentioned in the README for this reason.

**Comment by slxdy** [comment]
> You can use the tools. They are just very hard to use. Same as the csharp compiler these days. 
> 
> IkvmReference is the only thing mentioned in the README for this reason.
> 
> 

Wait a second, does IKVM actually generate C# code instead of directly building a CIL assembly?

**Comment by wasabii** [comment]
No.....

**Comment by slxdy** [comment]
> No.....

But why do you need the system assemblies then? You should only need to know whether youre targeting core or framework

**Comment by wasabii** [comment]
Because it needs to find types in them.

**Comment by slxdy** [comment]
> Because it needs to find types in them.

You dont actually. Type references can be made from pure names. Actually loading system libraries is just an extra unnecessary step

**Comment by wasabii** [comment]
We don't know what assemblies they live in unless we look.

**Comment by jameskunc** [comment]
I was able to derive the appropriate ikvmc parameters from these [IkvmImporterTests](https://github.com/ikvmnet/ikvm/blob/main/src/IKVM.Tools.Importer.Tests/IkvmImporterTests.cs).

The following parameters were required:

- **-lib:<dir>** => _Additional directories to search for references._  This needs to point to the target .NET Framework runtime path.
- **-runtime** => _Specifies the IKVM.Runtime.dll library to use._  This needs to point to the IKVM Runtime for the specified .NET framework's runtime.

For x86 .NET Framework 4.7.2:
`{ikvmc_path}\ikvmc.exe -target:library -out:"mylibrary.dll" "mylibrary.jar" -lib:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.2" -runtime:"{ikvm_runtime_path}\IKVM.Runtime.dll"`

To figure out the lib path, you can use the ToolLocationHelper class from Microsoft.Build.Utilities in combination with the params from the above unit test:
`ToolLocationHelper.GetPathToReferenceAssemblies(".NETFramework", "net472", "");`

This seemed to get past all of the errors I was running into.

**Comment by ImanCol** [comment]
Does the .dll only work on Windows? And how can I start calling Playit functions from code?
