### ISSUE TITLE
The type initializer for 'IKVM.Runtime.LibJvm' threw an exception. ---> System.NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by Tomazzzzz** [ikvmnet/ikvm#525]
Hello, I am trying to consume JAR file. Build is OK, but runtime am getting error on first hit java code.
Build is x86 windows .net472 & version of IKVM is 8.8.0.
As you can see this is very strange error.
THNX

The type initializer for 'com.ca.gen.jmmi.EncyManager' threw an exception.
System.TypeInitializationException: The type initializer for 'com.ca.gen.jmmi.EncyManager' threw an exception. ---> System.TypeInitializationException: The type initializer for 'com.ca.gen.jmmi.JMMILoader' threw an exception. ---> System.TypeInitializationException: The type initializer for 'java.lang.System' threw an exception. ---> System.TypeInitializationException: The type initializer for '<Module>' threw an exception. ---> System.TypeInitializationException: The type initializer for 'java.io.FileInputStream' threw an exception. ---> System.TypeInitializationException: The type initializer for 'IKVM.Runtime.LibJava' threw an exception. ---> System.TypeInitializationException: The type initializer for 'IKVM.Runtime.LibJvm' threw an exception. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at IKVM.Runtime.LibJvm..ctor()
   at IKVM.Runtime.LibJvm..cctor()
   --- End of inner exception stack trace ---
   at IKVM.Runtime.LibJava..ctor()
   at IKVM.Runtime.LibJava..cctor()
   --- End of inner exception stack trace ---
   at IKVM.Runtime.BootstrapClassLoader..ctor(RuntimeContext context)
   at IKVM.Runtime.RuntimeClassLoaderFactory.GetBootstrapClassLoader()
   at IKVM.Runtime.RuntimeClassLoaderFactory.GetClassLoaderWrapper(ClassLoader javaClassLoader)
   at IKVM.Runtime.RuntimeClassLoader.FromCallerID(CallerID callerID)
   at IKVM.Runtime.JNI.JNIFrame.GetFuncPtr(Object callerID, String clazz, String name, String sig)
   at java.io.FileInputStream.initIDs()
   at java.io.FileInputStream..cctor()
   --- End of inner exception stack trace ---
   at java.io.FileInputStream.__<clinit>()
   at java.lang.System.initializeSystemClass()
   at __<MethodAccessor>__System__initializeSystemClass()
   at IKVM.Runtime.Accessors.Java.Lang.SystemAccessor.InvokeInitializeSystemClass()
   at IKVM.Runtime.JVM.Init()
   at IKVM.Runtime.RuntimeInit.Init()
   at .cctor()
   --- End of inner exception stack trace ---
   at java.lang.System.registerNatives()
   at java.lang.System..cctor()
   --- End of inner exception stack trace ---
   at java.lang.System.getenv(String name)
   at com.ca.gen.jmmi.JMMILoader..cctor()
   --- End of inner exception stack trace ---
   at com.ca.gen.jmmi.JMMILoader.load()
   at com.ca.gen.jmmi.EncyManager..cctor()
   --- End of inner exception stack trace ---
   at com.ca.gen.jmmi.EncyManager.connectLocal(String str)

Project part:

<ItemGroup>

	  <IkvmReference Include="C:\Program Files (x86)\CA\Gen86\Gen\jmmi\jmmi.jar">
		  <AssemblyName>jmmi</AssemblyName>
		  <AssemblyVersion>8.8.0</AssemblyVersion>
		  <AssemblyFileVersion>8.8.0</AssemblyFileVersion>
		  <DisableAutoAssemblyName>true</DisableAutoAssemblyName>
		  <DisableAutoAssemblyVersion>true</DisableAutoAssemblyVersion>
		  <Debug>true</Debug>
	  </IkvmReference>
  </ItemGroup>

**Comment by wasabii** [comment]
In your product output, whether in the bin/ directory, or otherwise, is IKVM correctly copying the ikvm/{rid} folders?

For win-x86 there should be two, at least, win-x86 and win-x64. Each should contain bin/ and lib/, and bin/ should have jvm.dll present, iava.dll, etc.

**Comment by Tomazzzzz** [comment]
Yes, there are 2 folders ikvm & runtimes that contains all runtime, not only x86.
There is also ikvm.properties with : ikvm.home.root=ikvm
Also ProcMon showed that all DLL files were resolved and loaded.

**Comment by wasabii** [comment]
Any chance you can try it in 64 but, just to check?

**Comment by Tomazzzzz** [comment]
I must use x86, coz the Java is calling some win32 dll.
In any case, after running x64 I got different error: genmodel_client.dll: %1 is not a valid Win32 application
I don't know if it passed the previous error

**Comment by wasabii** [comment]
It did. Made it into IKVM, and attempted to load what sounds like a native library that is 32 bit. But it made it through IKVM.

So, we've got some issue specifically with the 32bit version of jvm.dll.

I think I probably know what the issue is.

It's kind of unfortunate, but I didn't want to put the automated tests for x86 in our CI/CD, since it takes a huge amount of time. That would have caught this.

**Comment by Tomazzzzz** [comment]
Actually I had issue with macOS, I could not build solution.
I will try to follow CONTRIBUTING file.

![image](https://github.com/ikvmnet/ikvm/assets/50398272/c6a07b01-f538-4d0a-86b8-20a8fff88822)

**Comment by Tomazzzzz** [comment]
Hello, is it possible to gen a new runtime files or nuget preview version?
