### ISSUE TITLE
IKVM 8.8.1 Winx64 (Graphic problem?)

### ISSUE THREAD

**Issue by merco** [ikvmnet/ikvm#539]
I get this exception:
org.jpedal.fonts.glyph.PdfJavaGlyphs.getUnscaledFont() in PdfJavaGlyphs.java

could it be some AWT related setting? How can I check if it is compatible with IKVM?

this is the code
![immagine](https://github.com/ikvmnet/ikvm/assets/1032335/eb480f72-ded0-4778-9bec-ca57eeebf208)

crash here

![immagine](https://github.com/ikvmnet/ikvm/assets/1032335/eeef950a-810e-4305-a4b7-1d3c3f3f003f)

**Comment by wasabii** [comment]
Yup. That's missing AWT. Nothing to be done until we release AWT support in 8.9

**Comment by merco** [comment]
Thank you wasabii! any idea of ​​the timing of the release date?

**Comment by wasabii** [comment]
Couple weeks I'm thinking.

**Comment by GeorgeS2019** [comment]
@merco 
If you go to the action and download artifact from the develop branch, try that to see if it works. I was able to use the awt integrated to create java GUI

**Comment by wasabii** [comment]
Please check with 8.9.0-pre.1.

**Comment by wasabii** [comment]
AWT is now in 8.9!
