### ISSUE TITLE
AWT Headless Exception with ImageJ.

### ISSUE THREAD

**Issue by BiologyTools** [ikvmnet/ikvm#542]
I'm trying to run ImageJ (ij.jar) using IKVM 8.8.1 but whenever I try to launch ImageJ I get the following error even when I set ImageJ to launch in headless mode or in normal mode.
```
using ij;
namespace FijiTest
{
    public partial class Form1 : Form
    {
        public Form1(string[] args)
        {
            InitializeComponent();
            var ijp = new ImageJ();
        }
    }
}
```
Here is the error I get.
```
java.awt.HeadlessException
  HResult=0x80131500
  Message=
  Source=IKVM.Java
  StackTrace:
   at java.awt.GraphicsEnvironment.checkHeadless()
   at java.awt.Window..ctor()
   at java.awt.Frame..ctor(String title)
   at ij.ImageJ..ctor(Applet applet, Int32 mode) in ImageJ.java:line 148
   at ij.ImageJ..ctor() in ImageJ.java:line 132
   at FijiTest.Form1..ctor(String[] args) in C:\Users\Kari\source\repos\FijiTest\FijiTest\Form1.cs:line 9
   at FijiTest.Program.Main(String[] args) in C:\Users\Kari\source\repos\FijiTest\FijiTest\Program.cs:line 14
```
[ImageJTest.zip](https://github.com/user-attachments/files/15936171/ImageJTest.zip)

I've attached a project which replicates the error.
Best, Erik

**Comment by GeorgeS2019** [comment]
@BiologyTools 
https://github.com/ikvmnet/ikvm/issues/144#issuecomment-2131934900

**Comment by BiologyTools** [comment]
@GeorgeS2019 Following your instructions using the develop branch I got ImageJ to run. However the buttons don't show up and instead show Chinese letters. Any idea on how to fix that issue?
![image](https://github.com/ikvmnet/ikvm/assets/84872500/31947450-1a51-4c02-9385-9d523bc903b5)

**Comment by GeorgeS2019** [comment]
This is something **yet to be addressed.** It seems to **only** happen in Windows and not linux. You may need to check that. 


<img src="https://github.com/ikvmnet/ikvm/assets/49812372/25e9ea58-c07b-4b1f-8c84-47a7d2bcafb4)" width=150>

**Comment by xela-trawets** [comment]
Looks like that might be a Unicode issue (32 bits Linux vs 16 bits on windows), errors on size or alignment in unicode often fall into chinese characters (there are so many more than Latin alphabets)

(I apologize for the drive by comment)

**Comment by GeorgeS2019** [comment]
How to solve

**Comment by BiologyTools** [comment]
@xela-trawets @GeorgeS2019  The encoding issue has already been solved at least on my Windows 11 machine ImageJ starts up normally. 
![image](https://github.com/user-attachments/assets/9a2168d6-2f84-46bd-91bc-c2f6c8da39dd)
