### ISSUE TITLE
C:\Users\xxx\.nuget\packages\ikvm\8.7.5\buildTransitive\IKVM.targets(98,9): error MSB4018: The "IkvmReferenceItemPrepare" task failed unexpectedly.

### ISSUE THREAD

**Issue by mserioli** [ikvmnet/ikvm#549]
Dear support,

since I checked out my project on a new workstation I'm getting the following error:

C:\Users\xxx\.nuget\packages\ikvm\8.7.5\buildTransitive\IKVM.targets(98,9): error MSB4018: The "IkvmReferenceItemPrepare" task failed unexpectedly.

C:\Users\xxx\.nuget\packages\ikvm\8.7.5\buildTransitive\IKVM.targets(98,9): error MSB4018: System.IO.InvalidDataException->Microsoft.Build.Framework.BuildException.GenericBuildTransferredException: End of Central Directory record could not be found.

I tried to clear the nuget packages folder and let VS recreate it but it dind't solved. I would say I'm stuck. Any hint?

My project is in  .net 8, developed on Visual Studio 2022. I reference the nuget package:

<PackageReference Include="IKVM.Maven.Sdk" Version="1.6.9" />

Thanks

**Comment by wasabii** [comment]
That's an error is since kind a about a zip file.... And of central directory....

It might be a corrupt jar?

**Comment by mserioli** [comment]
It was something I supposed..

I use IKVM to load:

<MavenReference Include="net.sf.saxon:Saxon-HE" version="12.3" />

Is there pewrhaps a jar caching directory where I can check?

Many trhanks

**Comment by wasabii** [comment]
I do not know what you are trying to actually do, so I can't answer that.

**Comment by wasabii** [comment]
Possible. Or a dependency. Or it's not pointing to a JAR file at all. That error is about the IkvmReferenceItemPrepare task not being able to parse a JAR file to determine an assembly name or version, I believe.

**Comment by mserioli** [comment]
Sincerely I'm a bit lost.

THe eror is pointing to IKWM.Targets

 
 <IkvmReferenceItemPrepare StateFile="$(_IkvmReferenceItemPrepareStateFile)" Items="@(IkvmReferenceItem)" ToolVersion="$(IkvmVersion)" ToolFramework="$(IkvmToolFramework)" RuntimeAssembly="$(IkvmRuntimeAssembly)" References="@(_IkvmReferenceReferences)" StageDir="$(IkvmStageDir)" CacheDir="$(IkvmCacheDir)">
     <Output TaskParameter="Items" ItemName="_IkvmReferenceItemWithMetadata" />
 </IkvmReferenceItemPrepare>

but doens't say more.

Is there a way to nealbe some loggin of what's happening?

THe thing is that same project is working  on another windows pc

**Comment by wasabii** [comment]
Could enable MSBuild binary logs and see the JAR files it is attempting to process, and then look at them.

**Comment by mserioli** [comment]
I see these errors that could possibly lead to the problem :

IKVM.MSBuild.Tasks.dll" in an external task host with a runtime of "CLR4" and a process architecture of "x64".



7>    Task Parameter:CacheDir=C:\Users\xxx\AppData\Local\Temp\ikvm\cache\1\
7>    Launching task "IkvmReferenceItemPrepare" from assembly "C:\Users\xxx\.nuget\packages\ikvm.msbuild\8.7.5\buildTransitive\..\tasks\net472\IKVM.MSBuild.Tasks.dll" in an external task host with a runtime of "CLR4" and a process architecture of "x64".
7>    Successfully loaded assembly info state.
7>    Successfully loaded file identity state.
7>    C:\Users\xxx\.nuget\packages\ikvm\8.7.5\buildTransitive\IKVM.targets(98,9): error MSB4018: The "IkvmReferenceItemPrepare" task failed unexpectedly.
7>    C:\Users\xxx\.nuget\packages\ikvm\8.7.5\buildTransitive\IKVM.targets(98,9): error MSB4018: System.IO.InvalidDataException->Microsoft.Build.Framework.BuildException.GenericBuildTransferredException: End of Central Directory record could not be found.
7>  Done executing task "IkvmReferenceItemPrepare" -- FAILED.

**Comment by wasabii** [comment]
Can you try enabling the MSBuild binary logger, increasing MSBuild logging verbosity to detailed, and seeing the JAR files that are actually being processed?

**Comment by mserioli** [comment]
Thank you man. 

![image](https://github.com/ikvmnet/ikvm/assets/2193904/88922184-268c-4c60-a1f3-9219a06d4fa1)


It pointed me out C:\Users\xxx\.m2\repository

which contained corrupted jar files :(

Removed them, rebuilt, and now it works,

Thanks again!

**Comment by wasabii** [comment]
Np
