### ISSUE TITLE
Unable to find a version of 'Mono.Posix' that is compatible with IKVM 8.8.1 

### ISSUE THREAD

**Issue by Velocedge** [ikvmnet/ikvm#552]
I have a 2022 Visual Studio .Net Framework 4.8 Windows Service project on Server 2019 written in C# that uses IKVM, currently version 8.1.5717 in production.  This is used by TikaOnDotnet.  When I try to upgrade to the latest version, 8.8.1, I get the error:

    Unable to find a version of 'Mono.Posix' that is compatible with 'IKVM 8.8.1 constraint: Mono.Posix (>= 7.1.0-final.1.21458.1)'.

Is this a known issue?  What can I do to upgrade to a more current version. It looks like I'm behind by close to 30 versions.

**Comment by wasabii** [comment]
I don't know what your project looks like... But the package is clearly right here: https://www.nuget.org/packages/Mono.Posix

Consider IKVM 8.2 however a complete rewrite. Everything has changed. New requirements, new methodologies, etc.
