### ISSUE TITLE
ServiceLoader.load() not enumerating services definition

### ISSUE THREAD

**Issue by AliveDevil** [ikvmnet/ikvm#572]
Repro: [serviceload.zip](https://github.com/user-attachments/files/16471477/serviceload.zip)

Actual behavior: UnsupportedOperationException thrown, with message "No scheme SIV_GCM".

Expected: Service Loader finds CryptorProvider service

**Comment by AliveDevil** [comment]
Setting
```
[assembly: CustomAssemblyClassLoader(typeof(AppDomainAssemblyClassLoader))]
```

In the `app.Launcher` resolves the issue, which is counter-intuitive.

**Comment by wasabii** [comment]
I think we resolved this by talking about ClassLoader stuff.
