### ISSUE TITLE
Replace IKVM.Reflection.Type system with System.Metadata.MetadataLoadContext

### ISSUE THREAD

**Issue by wasabii** [ikvmnet/ikvm#58]
One major component of the `IKVM.Reflection` project is a type hierarchy mirroring the standard System.Reflection types. Type, MethodInfo, FieldInfo, etc. In various buildables these types are used for assembly metadata reflection instead of the standard System.Reflection types. Likely because constructing the standard System.Reflection types required them to be loaded into an AppDomain.

System.Metadata, used by the Roslyn compiler, provides a number of capabilities that can replace this: namely a way to parse assembly metadata and expose it as the standard built-in system types, without requiring the assembly to be loaded into an AppDomain. It's likely the requirement for the divergent type hierarchy can be completely removed and replaced.

This would clear up a large bit of IKVM code, and remove many of the #ifdefs through out the project that alter the way the code runs based on which project the files are included in.

**Comment by bogatykh** [comment]
What was your idea behind this? Replace Universe with MetadataLoadContext?
For now mirrored Type system classes are tightly coupled with Emit system referenced in #59.

**Comment by wasabii** [comment]
Yup, that's the idea. The goal is to break one of the requirements for the divergent code paths (the IFDEFs for IMPORTER/EXPORTER). Bringing it one step closer to having the compiler code capable of being included as a separate assembly, instead of just include files. I'm removing the Good First Issue tag though, as now that I've been working on this half a year, I realize it's nowhere as easy as I thought.

**Comment by wasabii** [comment]
https://github.com/ikvm-revived/ikvm/discussions/186 reflections where my thinking is currently

**Comment by bogatykh** [comment]
> Yup, that's the idea. The goal is to break one of the requirements for the divergent code paths (the IFDEFs for IMPORTER/EXPORTER). Bringing it one step closer to having the compiler code capable of being included as a separate assembly, instead of just include files. I'm removing the Good First Issue tag though, as now that I've been working on this half a year, I realize it's nowhere as easy as I thought.

I was looking on how to implement this. Do you have any branch related to this?

**Comment by wasabii** [comment]
New plan here. We need an abstraction for Type, regardless, because we're going to need to swap System.Reflection.Emit for System.Reflection.Metadata.Ecma335. Additionally, in order to take care of the ref-assembly version of IKVM.Java for our xplat plan, we're going to be wanting to load up the RuntimeJavaType hierarchy without any code source at all, but from an API definition.

So, relying on Type, or something that looks like Type, just isn't going to cut it as an abstraction. We need something that can encapsulate the type information we need, and not be required to provide a full implementation of System.Type. IManagedType, likely.
