### ISSUE TITLE
SharedClassLoader support with IkvmReference?

### ISSUE THREAD

**Issue by HelloItMeMort** [ikvmnet/ikvm#588]
We're currently using ikvmc and would like to switch to using the more 'proper' IkvmReference method. Is there support for supplying a \<SharedClassLoader>true\</SharedClassLoader> in an IkvmReference?

**Comment by wasabii** [comment]
Nope. ShareClassLoader through IkvmReference isn't supported. Frankly, I'm currently not super sure where to go with the SharedClassLoader feature at all. Thinking of replacing it with some other functionality, like "class loader groups" or something.

The issue with shared class loader is it requires you compile multiple assemblies in a single execution of ikvmc. Using a weird '{}' syntax for inheriting command arguments. I plan to keep this working in ikvmc for the time being, but eventually to replace it with some different functionaly.

However, I haven't been able to come up with a modern use case which requires it. You can always use IkvmReference to merge multiple source files (JARs) into a single output assembly. Which at runtime, from the POV of Java, behaves the same as a shared class loader. Single assembly.

And if you're not doing that, you can also use a custom class loader, like the AppDomainAssemblyClassLoader, which makes resources and classes visible across the whole AppDomain.

I think future plans are going to probably include a replacement for SharedClassLoader, doing something like 'class loader groups'. Where you still run ikvmc multiple times, but assign each assembly to a 'group', which ends up being loaded by the same Java classloader at runtime. But that's not today.

**Comment by wasabii** [comment]
Yeah. You can stuff as many JAR files or class path directories in there as you want, and it'll produce one assembly. Might have to specify AssemblyName and version though since it might not be able to figure it out.
