### ISSUE TITLE
IKVM.Runtime.InternalException : Could not load libjvm

### ISSUE THREAD

**Issue by san-coder1** [ikvmnet/ikvm#598]
I am running my application from Azure Functions. It builds the .dll needed and places it in the bin folder in the Azure Function Runtime folders. `Assembly.LoadFile(modelsAssemblyPath);` also successfully loads the dll.

It fails with following error during var pipeline = new StanfordCoreNLP(props);

```
System.TypeInitializationException : The type initializer for '<Module>' threw an exception. ---> System.TypeInitializationException : The type initializer for '<Module>' threw an exception. ---> System.TypeInitializationException : The type initializer for 'IKVM.Runtime.LibJava' threw an exception. ---> System.TypeInitializationException : The type initializer for 'IKVM.Runtime.LibJvm' threw an exception. ---> IKVM.Runtime.InternalException : Could not load libjvm.
   at IKVM.Runtime.LibJvm..ctor()
   at IKVM.Runtime.LibJvm..cctor()
   End of inner exception
   at IKVM.Runtime.LibJava..ctor()
   at IKVM.Runtime.LibJava..cctor()
   End of inner exception
   at IKVM.Runtime.BootstrapClassLoader..ctor(RuntimeContext context)
   at IKVM.Runtime.RuntimeClassLoaderFactory.GetBootstrapClassLoader()
   at IKVM.Runtime.RuntimeClassLoaderFactory.GetClassLoaderWrapper(ClassLoader javaClassLoader)
   at IKVM.Runtime.JNI.JNIFrame.GetFuncPtr(Object callerID,String clazz,String name,String sig)
   at java.lang.System.initProperties(Properties props)
   at java.lang.System.initializeSystemClass()
   at __<MethodAccessor>__System__initializeSystemClass()
   at IKVM.Runtime.Accessors.Java.Lang.SystemAccessor.InvokeInitializeSystemClass()
   at IKVM.Runtime.JVM.Init()
   at IKVM.Runtime.RuntimeInit.Init()
   at .cctor()
   End of inner exception
   at ikvm.runtime.Startup.init()
   at .cctor()
   End of inner exception
```
I see ikvm folder in and jvm.dll in two places in my Azure Function directory.

c:\home\site\wwwroot\ikvm
c:\home\site\wwwroot\bin\ikvm
![image](https://github.com/user-attachments/assets/95b12103-8046-4752-a3db-cb22b3a4aa78)
c:\home\site\wwwroot\bin\ikvm\win-x64\bin> contains the jvm.dll
![image](https://github.com/user-attachments/assets/ffe1ee9c-61c1-406f-b1b2-0fb78d3cb85f)

I also tried to set ikvm.home.root and ikvm.home, but that did not work either.
![image](https://github.com/user-attachments/assets/1920fbfd-6a24-47f2-8356-4a28c7a05be8)

**Comment by wasabii** [comment]
I really do not know how function apps work.... But is this IIS? Is it using shadow copies? That might be related.

**Comment by san-coder1** [comment]
The code works on my local machine (C# solution). It breaks when it is deployed to Azure Functions.

**Comment by san-coder1** [comment]
@wasabii any idea for this? anything I can try?

**Comment by wasabii** [comment]
I do not. I know nothing of Azure Functions or how they work. Somebody is going to have to do some debugging on their end.

**Comment by MarkusSchmidtPro** [comment]
Same here with a .net 8 Console application on a quite fresh Win11 Pro machine:

```
---> System.TypeInitializationException: The type initializer for '<Module>' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'IKVM.Runtime.LibJava' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'IKVM.Runtime.LibJvm' threw an exception.
 ---> IKVM.Runtime.InternalException: **Could not load libjvm**.
 ```

It neither works with portable nor with x64 target.

From what I see the IKVM (portable) folder that contains the libraries for all target operating systems, does not contain a _libjvm.*_ library file for Windows (neither x64 nor x86), only for Linux and OSX.

Also to mention: on my Notebook it works. But there is a JVM installed! On my target machine (just setup) it does not. I am guessing, the missing library could be resolved when there is a JVM.

**Comment by wasabii** [comment]
Okaaay. Looks like some old functions in MSVCRT are still used for various C++ aspects of the OpenJDK code. May be able to work around those.... but for now, the current release still requires VCRT.

**Comment by MarkusSchmidtPro** [comment]
For me this is ok. I have adjusted the build process to copy the DLL to the bin folder.
Thanks MarkusS

18.10.2024 21:34:12 Jerome Haltom ***@***.***>:

**Comment by wasabii** [comment]
Also you could just install the VC++ redistributable.

**Comment by MarkusSchmidtPro** [comment]
Sure, as long as the app runs on my machine or on a well known target. If I want to publish my app to an unknown audience this complicates the setup, which is zero-copy right now.

Anyways, I am not sure about licensing and distribution of this single DLL. For me: this all is ok.

Others might think different. E g. deploying to Azure with that dependency. .. don't know ...

18.10.2024 22:21:29 Jerome Haltom ***@***.***>:

**Comment by wasabii** [comment]
Okay. So here's the word:

vcruntime140 is actually still required for some of the C++/C code from OpenJDK. Not really a way to work around it. I could bundle it in the IKVM package. But I think it's probably best to leave that up to the end developer. If you're building an app in IKVM, you need your installer to ensure the VCRedist is up to date. Or include your own copy.

https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2015-2017-2019-and-2022

I'm going to go ahead and close this for now. Nothing really to be done about it.

**Comment by san-coder1** [comment]
Thanks @wasabii, if we have updates and workaround, we will keep you posted.
