### ISSUE TITLE
Is command line compilation via ikvmc.exe no longer supported when statically converting Java bytecode to CIL?

### ISSUE THREAD

**Issue by kdaek21** [ikvmnet/ikvm#613]
I checked the contents of the comment that said to refer to 'https://github.com/orgs/ikvmnet/discussions/463' in the #612 I registered,

I saw the distinction IKVM.Runtime.Launcher.Run (string main, bool jar, string [] args, string rarg, IDictionary<string, string>properties), and in the comment there was something about Launcher, so I tried static conversion using ikvmc on the command line to see if the Spring Boot launcher part would be converted to IKVM.Runtime.Launcher.Run when using ikvmc for static conversion, but

Core library not found. Make sure the appropriate reference assemblies for the target environment are included. It only gives an error and does not convert. (It is the same even if I make a simple sample)

I looked it up and found that a similar issue was registered before, so I checked and it said to use ikvmReference. When I checked using ikvmReference, it seems to be a method of using jar files as libraries for .NET projects using Visual Studio.

Is there no longer a way to convert a class that contains a (Java) main function or a Java jar file that contains this class into a CIL exe file using ikvmc?

The IKVM tools used are IKVM-8.10.3-tools-net472-win-x64.

**Comment by wasabii** [comment]
It is. But there are a lot of options you need to add. -reference to the ref assemblies of the runtime version you want to bind to.

**Comment by kdaek21** [comment]
I found the default parameters for net472 version. If you do it like below, the conversion will work..
However, since only the assembly is created, the remaining necessary files must be created or copied separately to ensure normal operation. (Except for special cases such as Spring Boot)

ikvmc -r:"C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscorlib.dll" -r:"C:\Windows\Microsoft.NET\Framework64\v4.0.30319\System.dll" -runtime:"D:\Java\ikvm-jre8-net472\bin\IKVM.Runtime.dll" [classOrjar1] ... [classOrJarN]

- 'D:\Java\ikvm-jre8-net472\' is the path where IKVM-8.10.3-jre-net472-win-x64 is installed.

**Comment by wasabii** [comment]
Those are possible paths. But probably not the ones you want. When building you probably want to bind against the reference assemblies from the appropriate target framework version.

**Comment by mengke2815** [comment]
**I have the same problem，it  donesn’t work** 

![image](https://github.com/user-attachments/assets/b5a46e5e-d104-4c54-87c8-0695a55b2c22)

**Comment by kdaek21** [comment]
To statically convert for .NET Core, I found the following.
Example) Static conversion for net8.0

ikvmc -target:library -r:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.10\ref\net8.0\System.Runtime.dll" -runtime:"D:\Java\ikvm-jre8-net8.0\bin\IKVM.Runtime.dll" -nostdlib -main:[Class name including the package containing the main function] [classOrjar1] ... [classOrJarN]

* For net core, references are detailed, so in some cases you may need to add the -r option.
* Since it is converted to a library, it is essential to specify the class name including the package that contains the main function.
* [App name].runtimeconfig.json file must be created separately (copy one from ikvm-jdk or ikvm-jre, rename it, and use it)
* Since the executable file that automatically uploads the dll to the dotnet core runtime environment is not created, you must use it in the dotnet [App name].dll format, or learn the API for running the .NET Core app in C/C++ and implement it directly in C/C++ and use it
* For both the net472 method and the net core method, you must obtain peripheral files such as IKVM.Runtime and IKVM.Java from ikvm-jdk or ikvm-jre that are appropriate for each environment (IKVM.Java additionally varies depending on the OS environment, so checking the OS environment is essential)
* In the net core method, when creating [App name].runtimeconfig.json, simply obtain one from ikvm-jdk or ikvm-jre and use it. Since the default setting is self-contained execution when using it by changing the name, you also need to bring in the dotnet core libraries in ikvm-jdk or ikvm-jre.

I ended up finding what I wanted myself, so I'll close this issue.

**Comment by kdaek21** [comment]
> **I have the same problem，it donesn’t work**
> 
> ![image](https://private-user-images.githubusercontent.com/29645019/386490039-b5a46e5e-d104-4c54-87c8-0695a55b2c22.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2NTQzNjUsIm5iZiI6MTczMTY1NDA2NSwicGF0aCI6Ii8yOTY0NTAxOS8zODY0OTAwMzktYjVhNDZlNWUtZDEwNC00YzU0LTg3YzgtMDY5NWE1NWIyYzIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE1VDA3MDEwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5ZmNhMDg2NDdlNzYxNDMwMjRjNTYwNWEzMTY2NjQyMTg2NWU3NzcxZTc0MzBmZTI3ZjhjZGQzNTQ4ZDllYWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.M2Su0MB0QFRTPouk6qWb3F4ZOz9Iyf7IcLxD0U8sgkQ)

I was adding information about net core, and you answered it again..
net core needs to be compiled properly with the -nostdlib option.

**Comment by mengke2815** [comment]
thanks

**Comment by mengke2815** [comment]
I have another problem，can you help me

![image](https://github.com/user-attachments/assets/07d4805c-d957-490c-a1b4-473cd637a741)

**Comment by kdaek21** [comment]
> I have another problem，can you help me
> 
> ![image](https://private-user-images.githubusercontent.com/29645019/386496433-07d4805c-d957-490c-a1b4-473cd637a741.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2NTY1NzUsIm5iZiI6MTczMTY1NjI3NSwicGF0aCI6Ii8yOTY0NTAxOS8zODY0OTY0MzMtMDdkNDgwNWMtZDk1Ny00OTBjLWExYjQtNDczY2Q2MzdhNzQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE1VDA3Mzc1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3MTVlZWE0ZTVmYTY1OGJlMDAyNDk4OTY3M2VhNDRjYTM1OTA0ZjAxNWVjZGZhYmY3NzZmNzQ2MTE3ZmRjNWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.9ridGeaQnraittpIUvDzYrHxlAEO-XMWgyiMr_t1lb4)

net core requires more references than net472. Below is the compilation syntax that I tested with Tomcat. When compiling Tomcat...

System.Runtime.dll is required by default,
and Systme.Console.dll, System.Threading.dll, and System.Threading.Thread.dll were additionally required.

ikvmc -target:library -r:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.10\ref\net8.0\System.Runtime.dll" -r:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.10\ref\net8.0\System.Console.dll" -r:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.10\ref\net8.0\System.Threading.dll" -r:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.10\ref\net8.0\System.Threading.Thread.dll" -runtime:"D:\Java\ikvm-jre8-net8.0\bin\IKVM.Runtime.dll" -recurse:"./lib" -nostdlib -main:"org.apache.catalina.startup.Bootstrap" bootstrap.jar tomcat-juli.jar

**Comment by mengke2815** [comment]
> > I have another problem，can you help me
> > ![image](https://private-user-images.githubusercontent.com/29645019/386496433-07d4805c-d957-490c-a1b4-473cd637a741.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2NTY1NzUsIm5iZiI6MTczMTY1NjI3NSwicGF0aCI6Ii8yOTY0NTAxOS8zODY0OTY0MzMtMDdkNDgwNWMtZDk1Ny00OTBjLWExYjQtNDczY2Q2MzdhNzQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE1VDA3Mzc1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3MTVlZWE0ZTVmYTY1OGJlMDAyNDk4OTY3M2VhNDRjYTM1OTA0ZjAxNWVjZGZhYmY3NzZmNzQ2MTE3ZmRjNWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.9ridGeaQnraittpIUvDzYrHxlAEO-XMWgyiMr_t1lb4)
> 
> net core requires more references than net472. Below is the compilation syntax that I tested with Tomcat. When compiling Tomcat...
> 
> System.Runtime.dll is required by default, and Systme.Console.dll, System.Threading.dll, and System.Threading.Thread.dll were additionally required.
> 
> ikvmc -target:library -r:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.10\ref\net8.0\System.Runtime.dll" -r:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.10\ref\net8.0\System.Console.dll" -r:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.10\ref\net8.0\System.Threading.dll" -r:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.10\ref\net8.0\System.Threading.Thread.dll" -runtime:"D:\Java\ikvm-jre8-net8.0\bin\IKVM.Runtime.dll" -recurse:"./lib" -nostdlib -main:"org.apache.catalina.startup.Bootstrap" bootstrap.jar tomcat-juli.jar

oh，i understand，thanks very much~!
