### ISSUE TITLE
Multiple RuntimeIdentifiers targeting more than selected .NET 8.0

### ISSUE THREAD

**Issue by mtmulch0191** [ikvmnet/ikvm#621]
I have the following configuration in my API's main .csproj. So I want to target win-x64 and win-x86 but when I publish the project I get the entire target set from IKVM.
![image](https://github.com/user-attachments/assets/aa6b27b1-4884-4965-9924-1a6f223b115d)
![image](https://github.com/user-attachments/assets/c5b43fb1-ad9c-4602-b4ec-c5dae5467128)

However if I change `<RuntimeIdentifiers>` to `<RuntimeIdentifier>` and target a singular RID it will only output the win-x64.
![image](https://github.com/user-attachments/assets/3a3bb646-eea7-4dec-8fb5-94017e26508f)
![image](https://github.com/user-attachments/assets/12accd1c-90cf-4e6f-ad6e-5c2ed3de097e)

I have to confirm our need for x64 and x86 but I believe x64 should sufficient but I wanted to report this for the project.

**Comment by mtmulch0191** [comment]
I am using `dotnet publish` and I also tried publishing to a local folder with Visual Studio.

**Comment by wasabii** [comment]
Try specifying a RID when you publish?

**Comment by wasabii** [comment]
https://learn.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props#runtimeidentifiers

The RuntimeIdentifiers property lets you specify a semicolon-delimited list of [runtime identifiers (RIDs)](https://learn.microsoft.com/en-us/dotnet/core/rid-catalog) for the project. Use this property if you need to publish for multiple runtimes. RuntimeIdentifiers is used at restore time to ensure the right assets are in the graph.

**Comment by mtmulch0191** [comment]
I was able to get this to work locally on my machine with `dotnet publish -r win-x64 --self-contained`. I have some runtime dependencies issues that need to be resolve locally but even with `--self-contained` my bundle size is drastically smaller due to IKVM targets not being available and the ASP .NET Core runtimes folder.

**Comment by wasabii** [comment]
Correct. Publishing for win-x86 will however also include the win-x64 versions, unless Prefer32Bit is set. Since 32 bit .NET apps running
