### ISSUE TITLE
Cant reference to jar file with Java 11 or higher 

### ISSUE THREAD

**Issue by hungmanhhoang963** [ikvmnet/ikvm#624]
Hi, I'm try to use IKVM to convert jar to dll using IKVMReference. I tried to create 2 java file, one is java 6 and the other is java 11.
The java 6 file can reference but the java 11 can not. Is IKVM only support java 8 right ?. If so, in the future will IKVM support higher version of Java

**Comment by AliveDevil** [comment]
#120, JDK 8 that's all.
