### ISSUE TITLE
DisableOptimization set when DebugType is set

### ISSUE THREAD

**Issue by ShaneHuHu** [ikvmnet/ikvm#631]
Hello Sir

I made a simple sample application to compre performance. This is my java code:

            public class TestClass {
	            private float calcAvg(float[] array){
		            float sum = 0;
		            for(int i = 0 ; i < array.length; ++i)
			            sum += array[i];
		            return sum / array.length;
	            }
	            public void test(){
		            float[] array = new float[1024*1024*6];
		            for(int i = 0 ; i < array.length; ++i)
			            array[i] = i;
		            
		            Date date = new Date();
		            for(int i = 0; i < 100; ++i)
			            calcAvg(array);
		            System.out.println((new Date().getTime() - date.getTime()) / 1000f + " sec.");
	            }
            }

This is my C# code:

            private float calcAvg(float[] array)
            {
                float sum = 0;
                for (int i = 0; i < array.Length; ++i)
                    sum += array[i];
                return sum / array.Length;
            }
            public void testCS()
            {
                var array = new float[1024 * 1024 * 6];
                for (int i = 0; i < array.Length; ++i)
                    array[i] = i;
                var time = DateTime.Now;
                for (int i = 0; i < 100; ++i)
                    calcAvg(array);
                Console.WriteLine((DateTime.Now - time).TotalSeconds + " Sec");
            }

This is my compare result:
    java:  0.659 sec
    C#:  0.589 sec
    IKVM compiled java: 1.901 sec

May I ask for your help how  to improve the performance Sir?

Thanks

**Comment by wasabii** [comment]
Are you measuring performance of the code itself, or the time it takes to start?

**Comment by ShaneHuHu** [comment]
This is the IDL code of IKVM
    .method private hidebysig instance float32 
            calcAvg(float32[] 'array') cil managed
    {
      // Code size       42 (0x2a)
      .maxstack  3
      .locals init (float32 V_0,
               int32 V_1,
               bool V_2,
               float32 V_3)
      IL_0000:  nop
      IL_0001:  ldc.r4     0.0
      IL_0006:  stloc.0
      IL_0007:  ldc.i4.0
      IL_0008:  stloc.1
      IL_0009:  br.s       IL_0015
      IL_000b:  ldloc.0
      IL_000c:  ldarg.1
      IL_000d:  ldloc.1
      IL_000e:  ldelem.r4
      IL_000f:  add
      IL_0010:  stloc.0
      IL_0011:  ldloc.1
      IL_0012:  ldc.i4.1
      IL_0013:  add
      IL_0014:  stloc.1
      IL_0015:  ldloc.1
      IL_0016:  ldarg.1
      IL_0017:  ldlen
      IL_0018:  conv.i4
      IL_0019:  clt
      IL_001b:  stloc.2
      IL_001c:  ldloc.2
      IL_001d:  brtrue.s   IL_000b
      IL_001f:  ldloc.0
      IL_0020:  ldarg.1
      IL_0021:  ldlen
      IL_0022:  conv.i4
      IL_0023:  conv.r4
      IL_0024:  div
      IL_0025:  stloc.3
      IL_0026:  br.s       IL_0028
      IL_0028:  ldloc.3
      IL_0029:  ret
    } // end of method TestClassX::calcAvg

This is C#
    .method private hidebysig instance float32 
            calcAvg(float32[] 'array') cil managed
    {
      // Code size       33 (0x21)
      .maxstack  3
      .locals init (float32 V_0,
               int32 V_1)
      IL_0000:  ldc.r4     0.0
      IL_0005:  stloc.0
      IL_0006:  ldc.i4.0
      IL_0007:  stloc.1
      IL_0008:  br.s       IL_0014
      IL_000a:  ldloc.0
      IL_000b:  ldarg.1
      IL_000c:  ldloc.1
      IL_000d:  ldelem.r4
      IL_000e:  add
      IL_000f:  stloc.0
      IL_0010:  ldloc.1
      IL_0011:  ldc.i4.1
      IL_0012:  add
      IL_0013:  stloc.1
      IL_0014:  ldloc.1
      IL_0015:  ldarg.1
      IL_0016:  ldlen
      IL_0017:  conv.i4
      IL_0018:  blt.s      IL_000a
      IL_001a:  ldloc.0
      IL_001b:  ldarg.1
      IL_001c:  ldlen
      IL_001d:  conv.i4
      IL_001e:  conv.r4
      IL_001f:  div
      IL_0020:  ret
    } // end of method TestClassX::calcAvg
    
I trided different <Debug> options, but it doesn't help~~~~

**Comment by ShaneHuHu** [comment]
I export il code and recompile by ilasm. The performance is good but I don't understand what happened~~~. May I ask for your help Sir?

**Comment by wasabii** [comment]
So, I built a benchmark. Same two tasks as you: initialize an array with items, average array 100 times. In both C# and Java in IKVM. And they are equiv in speed. So I don't see anything wrong.

**Comment by ShaneHuHu** [comment]
@wasabii I use dotnet4.7.2, would it impact?

**Comment by wasabii** [comment]
Its almost the exact same IL, so no.

**Comment by ShaneHuHu** [comment]
@wasabii Yes, the IL doesn't matter and I recompile by ilasm, it improve the performance also. Just I don't understand what's the different.

**Comment by wasabii** [comment]
Perhaps. In your IKVM assembly, is DebuggableAttribute set to disable optimizations?

**Comment by ShaneHuHu** [comment]
Nope sir,  I didn't do anything

**Comment by wasabii** [comment]
Well check.

**Comment by wasabii** [comment]
Yup. That'll do it then.

Will need to fix the code for the next release.

**Comment by wasabii** [comment]
Or you can turn off debug symbols.

**Comment by ShaneHuHu** [comment]
@wasabii Hwo I could do it Sir?

**Comment by wasabii** [comment]
Since it's all conditional on EmitSymbols, and that is set by -debug other than none, you can disable generation of symbols for the project. In VS it's some option somewhere.

**Comment by ShaneHuHu** [comment]
@wasabii Thank you so much Sir, I'll wait for the next release. Thank you!!!!!

**Comment by wasabii** [comment]
Looks like IkvmReference.Debug governs this. And that is defaulted to $(DebugType), so it's governed by the debug type of the project you are building. If you were to disable debug symbols on the project that should do it. Or you can explicitely add the Debug metadata to IkvmReference.

**Comment by wasabii** [comment]
Should be solved in develop.
