### ISSUE TITLE
System.IO.FileNotFoundException: Reference assemblies directory: packs

### ISSUE THREAD

**Issue by superstrom** [ikvmnet/ikvm#78]
Extract the netcoreapp3.1 tools to d:\dev\IKVM-8.2.0-prerelease.809-tools-netcoreapp3.1-win7-x64\ and add to PATH.

```
>> ikvmc.exe test.jar -out:test.dll
IKVM.NET Compiler (8.2.0-prerelease.809)
...

ikvmc, Version=8.2.0.0 ...
d:\dev\IKVM-8.2.0-prerelease.809-tools-netcoreapp3.1-win7-x64\
3.1.25 64-bit

System.IO.FileNotFoundException: Reference assemblies directory: packs\dev.Ref\3.1.0\ref\netcoreapp3.1
at IKVM.Reflection.Universe.BuildRefDirFrom(String runtimeDir) in D:\a\ikvm\ikvm\IKVM.Reflection\Universe.cs:line 180
at IKVM.Reflection.Universe.get_ReferenceAssembiesDirectory() in  D:\a\ikvm\ikvm\IKVM.Reflection\Universe.cs:line 156
at IKVM.Reflection.Universe.DefaultResolver(String refName, Boolean throwOnError) in  D:\a\ikvm\ikvm\IKVM.Reflection\Universe.cs:line 842
at IKVM.Reflection.Universe.Load(String refName, Module requestingModule, Boolean throwOnError) in  D:\a\ikvm\ikvm\IKVM.Reflection\Universe.cs:line 799
at IKVM.Internal.AssemblyResolver.Init(Universe universe, Boolean nostdlib, IList`1 references, IList`1 userLibPaths) in  D:\a\ikvm\ikvm\ikvmc\IKVM\Internal\AssemblyResolver.cs:line 93
at ikvmc.IkvmcComplier.Compile(String[] args) in D:\a\ikvm\ikvm\ikvmc\IkvmcCompiler.cs:line 178
at ikvmc.IkvmcComplier.Main(String[] args) in D:\a\ikvm\ikvm\ikvmc\IkvmcCompiler.cs:line 112
```

RuntimeEnvironment.GetRuntimeDirectory() returns the location of ikvmc.exe rather than the current dotnet runtime dir as BuildRefDirFrom seems to expect.

**Comment by NightOwl888** [comment]
The plan is to remove the `-nostdlib` option on `ikvmc` and make that the default. For now, it attempts (poorly) to resolve the directory based on convention.

However, you can override this convention by specifying `-nostdlib -lib:<dir>`. The reference assemblies for .NET Core 3.1 are in the `<ikvmtools>/ref` folder, but if that doesn't work you can either try one of the .NET SDK folders or download the [.NET Core Reference Assemblies](https://www.nuget.org/packages/Microsoft.NETCore.App.Ref).

**Comment by JanusTida** [comment]
> The plan is to remove the `-nostdlib` option on `ikvmc` and make including it the default setting. For now, it attempts (poorly) to resolve the directory based on convention.
> 
> However, you can override this convention by specifying `-nostdlib -r:<ikvmtools>/refs/*.dll`.
I override the convention: 
`ikvmc Tianyu.EML.jar -target:library -nostdlib -r:C:\Apps\IKVM-8.2.0\refs\*.dll'
but still got the error message:
`IKVM.NET Compiler (8.2.0-prerelease.809)
Copyright ? 2022 Jeroen Frijters, Windward Studios, Jerome Haltom, Shad Storhaug

Error: unable to find mscorlib.dll`

**Comment by NightOwl888** [comment]
@JanusTida 

Yea, I just noticed that problem yesterday. The globs don't seem to be working on the `-r` option when you specify absolute path. However, if you `cd` into the `<ikvmtools>` directory and use absolute paths on the `jar` and other bits you are pulling in and a relative path on `<ikvmtools>` (`-r:./refs/*.dll`), then it finds the reference assemblies.

You may still receive a warning that it found multiple copies of `netstandard.dll`, but that issue isn't causing any known issues at runtime.

**Comment by wasabii** [comment]
I have removed all of the auto detection directory stuff at this point, so it's no longer a thing, since it was pretty broken.

So, at a minimum, this bug is closed, since it's about the missing directory. That won't happen anymore. You still need to specify the references.
